"""Remove status field from Task model

Revision ID: 0837d54a83b6
Revises: fa4773f088dc
Create Date: 2025-04-10 10:51:18.432285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0837d54a83b6'
down_revision = 'fa4773f088dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('marker', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('file_paths', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_logs')
    with op.batch_alter_table('tasks') as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
