"""Remove status field from tasks table

Revision ID: 8546459c0702
Revises: 7b1c884ef8c0
Create Date: 2025-04-10 12:09:33.348237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8546459c0702'
down_revision = '7b1c884ef8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
