"""add x2,y2,w2,h2 fields to marker_config

Revision ID: c2e967457f05
Revises: 20250721_add_mid2
Create Date: 2025-08-01 16:03:41.928042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e967457f05'
down_revision = '20250721_add_mid2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marker_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('x2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('y2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('w2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('h2', sa.Integer(), nullable=True))
        batch_op.alter_column('mid2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'00000000000'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marker_config', schema=None) as batch_op:
        batch_op.alter_column('mid2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'00000000000'"))
        batch_op.drop_column('h2')
        batch_op.drop_column('w2')
        batch_op.drop_column('y2')
        batch_op.drop_column('x2')

    # ### end Alembic commands ###
