# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20026 import InlineResponse20026  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20026(unittest.TestCase):
    """InlineResponse20026 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026(self):
        """Test InlineResponse20026"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20026.InlineResponse20026()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
