# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.artifact_api import ArtifactApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArtifactApi(unittest.TestCase):
    """ArtifactApi unit test stubs"""

    def setUp(self):
        self.api = ArtifactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_lines(self):
        """Test case for add_lines

        添加虚拟线段  # noqa: E501
        """
        pass

    def test_add_pois(self):
        """Test case for add_pois

        添加POI  # noqa: E501
        """
        pass

    def test_add_rectangle_area(self):
        """Test case for add_rectangle_area

        添加矩形区域  # noqa: E501
        """
        pass

    def test_adjust_pois(self):
        """Test case for adjust_pois

        优化POI位姿  # noqa: E501
        """
        pass

    def test_clear_lines(self):
        """Test case for clear_lines

        清空某一类虚拟线段  # noqa: E501
        """
        pass

    def test_clear_pois(self):
        """Test case for clear_pois

        清空POI  # noqa: E501
        """
        pass

    def test_clear_rectangle_areas(self):
        """Test case for clear_rectangle_areas

        清空某一类矩形区域  # noqa: E501
        """
        pass

    def test_delete_laser_landmarks(self):
        """Test case for delete_laser_landmarks

        清空激光地标  # noqa: E501
        """
        pass

    def test_delete_poi(self):
        """Test case for delete_poi

        删除POI  # noqa: E501
        """
        pass

    def test_edit_rectangle_area(self):
        """Test case for edit_rectangle_area

        编辑矩形区域  # noqa: E501
        """
        pass

    def test_get_current_pois(self):
        """Test case for get_current_pois

        获取当前地图中的所有POI  # noqa: E501
        """
        pass

    def test_get_laser_landmark_update(self):
        """Test case for get_laser_landmark_update

        获取激光地标更新状态  # noqa: E501
        """
        pass

    def test_get_laser_landmarks(self):
        """Test case for get_laser_landmarks

        获取激光地标  # noqa: E501
        """
        pass

    def test_get_lines(self):
        """Test case for get_lines

        获取虚拟线段  # noqa: E501
        """
        pass

    def test_get_poi_by_id(self):
        """Test case for get_poi_by_id

        根据ID查找POI  # noqa: E501
        """
        pass

    def test_get_rectangle_areas(self):
        """Test case for get_rectangle_areas

        获取矩形区域  # noqa: E501
        """
        pass

    def test_modify_lines(self):
        """Test case for modify_lines

        修改虚拟线段  # noqa: E501
        """
        pass

    def test_modify_poi(self):
        """Test case for modify_poi

        修改POI  # noqa: E501
        """
        pass

    def test_put_laser_landmarks(self):
        """Test case for put_laser_landmarks

        设置激光地标  # noqa: E501
        """
        pass

    def test_remove_laser_landmarks(self):
        """Test case for remove_laser_landmarks

        删除激光地标  # noqa: E501
        """
        pass

    def test_remove_line_by_id(self):
        """Test case for remove_line_by_id

        删除虚拟线段  # noqa: E501
        """
        pass

    def test_remove_rectangle_area_by_id(self):
        """Test case for remove_rectangle_area_by_id

        删除矩形区域  # noqa: E501
        """
        pass

    def test_set_laser_landmark_update(self):
        """Test case for set_laser_landmark_update

        设置取激光地标更新状态  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
