# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sensors_api import SensorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_disabled_sensors_mask_data(self):
        """Test case for get_disabled_sensors_mask_data

        获取传感器禁用状态  # noqa: E501
        """
        pass

    def test_set_depth_sensor_state(self):
        """Test case for set_depth_sensor_state

        使能/禁用深度摄像头数据  # noqa: E501
        """
        pass

    def test_set_sensor_mask(self):
        """Test case for set_sensor_mask

        使能/禁用传感器  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
