# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.multi_floor_api import MultiFloorApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMultiFloorApi(unittest.TestCase):
    """MultiFloorApi unit test stubs"""

    def setUp(self):
        self.api = MultiFloorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_map(self):
        """Test case for delete_map

        删除保存的地图  # noqa: E501
        """
        pass

    def test_dispatch_by_pois(self):
        """Test case for dispatch_by_pois

        查询POI的最优遍历顺序  # noqa: E501
        """
        pass

    def test_get_all_pois(self):
        """Test case for get_all_pois

        获取POI信息  # noqa: E501
        """
        pass

    def test_get_current_floor(self):
        """Test case for get_current_floor

        获取机器人所在楼层信息  # noqa: E501
        """
        pass

    def test_get_current_home_dock(self):
        """Test case for get_current_home_dock

        获取绑定的充电桩  # noqa: E501
        """
        pass

    def test_get_elevators(self):
        """Test case for get_elevators

        获取电梯区域  # noqa: E501
        """
        pass

    def test_get_elevators_by_id(self):
        """Test case for get_elevators_by_id

        获取某个电梯的信息  # noqa: E501
        """
        pass

    def test_get_floors(self):
        """Test case for get_floors

        获取所有楼层信息  # noqa: E501
        """
        pass

    def test_get_mutil_floor_home_docks(self):
        """Test case for get_mutil_floor_home_docks

        获取充电桩信息  # noqa: E501
        """
        pass

    def test_get_pose_relation_to_elevator(self):
        """Test case for get_pose_relation_to_elevator

        获取机器人与电梯的位置关系  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        获取地图状态信息  # noqa: E501
        """
        pass

    def test_reload_stcm(self):
        """Test case for reload_stcm

        重新加载地图  # noqa: E501
        """
        pass

    def test_save_stcm(self):
        """Test case for save_stcm

        持久化保存当前地图  # noqa: E501
        """
        pass

    def test_search_nearby_home_dock(self):
        """Test case for search_nearby_home_dock

        查找离机器人最近的充电桩  # noqa: E501
        """
        pass

    def test_search_nearby_poi(self):
        """Test case for search_nearby_poi

        查找最近的POI  # noqa: E501
        """
        pass

    def test_search_path_points_in_graph(self):
        """Test case for search_path_points_in_graph

        通过轨道搜索路径点  # noqa: E501
        """
        pass

    def test_set_current_floor(self):
        """Test case for set_current_floor

        设置机器人所在楼层信息  # noqa: E501
        """
        pass

    def test_set_current_home_dock(self):
        """Test case for set_current_home_dock

        绑定充电桩  # noqa: E501
        """
        pass

    def test_set_pose_by_homedock(self):
        """Test case for set_pose_by_homedock

        根据充电桩重置机器人定位  # noqa: E501
        """
        pass

    def test_set_pose_by_poi(self):
        """Test case for set_pose_by_poi

        设置机器人位姿  # noqa: E501
        """
        pass

    def test_sync_stcm(self):
        """Test case for sync_stcm

        同步地图  # noqa: E501
        """
        pass

    def test_unbind_scene(self):
        """Test case for unbind_scene

        解绑云端场景  # noqa: E501
        """
        pass

    def test_upload_map(self):
        """Test case for upload_map

        上传地图到机器人  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
