# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.industry_api import IndustryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIndustryApi(unittest.TestCase):
    """IndustryApi unit test stubs"""

    def setUp(self):
        self.api = IndustryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_task_template(self):
        """Test case for create_task_template

        创建任务模板  # noqa: E501
        """
        pass

    def test_delete_task_template(self):
        """Test case for delete_task_template

        删除任务模板  # noqa: E501
        """
        pass

    def test_get_industry_tasks(self):
        """Test case for get_industry_tasks

        查询任务信息  # noqa: E501
        """
        pass

    def test_get_task_templates(self):
        """Test case for get_task_templates

        获取任务模板  # noqa: E501
        """
        pass

    def test_post_task_event(self):
        """Test case for post_task_event

        推送任务事件  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
