# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_api import SystemApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_robot_health(self):
        """Test case for clear_robot_health

        清除出错的状态信息  # noqa: E501
        """
        pass

    def test_get_battery_pack(self):
        """Test case for get_battery_pack

        获取电池包的电流和温度  # noqa: E501
        """
        pass

    def test_get_capabilities(self):
        """Test case for get_capabilities

        获取机器人能力  # noqa: E501
        """
        pass

    def test_get_cmlink_apn(self):
        """Test case for get_cmlink_apn

        获取cmlink apn  # noqa: E501
        """
        pass

    def test_get_imu_raw_adc_data(self):
        """Test case for get_imu_raw_adc_data

        获取IMU的ADC原始值  # noqa: E501
        """
        pass

    def test_get_imu_raw_data(self):
        """Test case for get_imu_raw_data

        获取IMU原始值  # noqa: E501
        """
        pass

    def test_get_jack_status(self):
        """Test case for get_jack_status

        获取千斤顶状态  # noqa: E501
        """
        pass

    def test_get_laser_scan(self):
        """Test case for get_laser_scan

        获取当前激光观测帧  # noqa: E501
        """
        pass

    def test_get_network_route(self):
        """Test case for get_network_route

        获取路由信息  # noqa: E501
        """
        pass

    def test_get_network_status(self):
        """Test case for get_network_status

        获取网络状态  # noqa: E501
        """
        pass

    def test_get_power_status(self):
        """Test case for get_power_status

        获取机器人电源状态  # noqa: E501
        """
        pass

    def test_get_robot_health(self):
        """Test case for get_robot_health

        获取设备健康状态信息  # noqa: E501
        """
        pass

    def test_get_robot_info(self):
        """Test case for get_robot_info

        获取设备信息  # noqa: E501
        """
        pass

    def test_get_system_parameter(self):
        """Test case for get_system_parameter

        获取系统参数  # noqa: E501
        """
        pass

    def test_hibernate(self):
        """Test case for hibernate

        休眠机器人  # noqa: E501
        """
        pass

    def test_restart_module(self):
        """Test case for restart_module

        重启模块  # noqa: E501
        """
        pass

    def test_set_aeb_control(self):
        """Test case for set_aeb_control

        设置AEB控制  # noqa: E501
        """
        pass

    def test_set_cmlink_apn(self):
        """Test case for set_cmlink_apn

        设置cmlink apn  # noqa: E501
        """
        pass

    def test_set_cube_config(self):
        """Test case for set_cube_config

        设置Cube配置  # noqa: E501
        """
        pass

    def test_set_jack_req(self):
        """Test case for set_jack_req

        设置千斤顶状态  # noqa: E501
        """
        pass

    def test_set_light_control(self):
        """Test case for set_light_control

        设置灯光控制效果  # noqa: E501
        """
        pass

    def test_set_network_route(self):
        """Test case for set_network_route

        设置路由信息  # noqa: E501
        """
        pass

    def test_set_network_status(self):
        """Test case for set_network_status

        设置网络状态  # noqa: E501
        """
        pass

    def test_set_system_parameter(self):
        """Test case for set_system_parameter

        设置系统参数  # noqa: E501
        """
        pass

    def test_shutdown(self):
        """Test case for shutdown

        关闭或重启机器人  # noqa: E501
        """
        pass

    def test_wakeup(self):
        """Test case for wakeup

        唤醒机器人  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
