# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.platform_api import PlatformApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlatformApi(unittest.TestCase):
    """PlatformApi unit test stubs"""

    def setUp(self):
        self.api = PlatformApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_events(self):
        """Test case for get_events

        获取事件信息  # noqa: E501
        """
        pass

    def test_get_timestamp(self):
        """Test case for get_timestamp

        获取系统时间戳  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
