# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.task_template import TaskTemplate  # noqa: E501
from swagger_client.rest import ApiException


class TestTaskTemplate(unittest.TestCase):
    """TaskTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskTemplate(self):
        """Test TaskTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.task_template.TaskTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
