# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.v1_parameter_body import V1ParameterBody  # noqa: E501
from swagger_client.rest import ApiException


class TestV1ParameterBody(unittest.TestCase):
    """V1ParameterBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1ParameterBody(self):
        """Test V1ParameterBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.v1_parameter_body.V1ParameterBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
