# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.application_api import ApplicationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_app(self):
        """Test case for delete_app

        卸载一个APP  # noqa: E501
        """
        pass

    def test_get_apps(self):
        """Test case for get_apps

        获取所有自定义安装的APP  # noqa: E501
        """
        pass

    def test_install_app(self):
        """Test case for install_app

        安装APP  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
