# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.homedocks_dock_id_body import HomedocksDockIdBody  # noqa: E501
from swagger_client.rest import ApiException


class TestHomedocksDockIdBody(unittest.TestCase):
    """HomedocksDockIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHomedocksDockIdBody(self):
        """Test HomedocksDockIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.homedocks_dock_id_body.HomedocksDockIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
