# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.delivery_api import DeliveryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeliveryApi(unittest.TestCase):
    """DeliveryApi unit test stubs"""

    def setUp(self):
        self.api = DeliveryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_all_tasks(self):
        """Test case for cancel_all_tasks

        取消所有任务  # noqa: E501
        """
        pass

    def test_cancel_task_by_order_id(self):
        """Test case for cancel_task_by_order_id

        根据订单ID取消任务  # noqa: E501
        """
        pass

    def test_cancel_task_by_task_id(self):
        """Test case for cancel_task_by_task_id

        根据Task ID取消任务  # noqa: E501
        """
        pass

    def test_create_task(self):
        """Test case for create_task

        创建任务  # noqa: E501
        """
        pass

    def test_create_tasks(self):
        """Test case for create_tasks

        批量创建任务  # noqa: E501
        """
        pass

    def test_end_operation(self):
        """Test case for end_operation

        完成操作  # noqa: E501
        """
        pass

    def test_end_pickup(self):
        """Test case for end_pickup

        结束取物  # noqa: E501
        """
        pass

    def test_end_task(self):
        """Test case for end_task

        结束所有任务  # noqa: E501
        """
        pass

    def test_get_assigned_cargos(self):
        """Test case for get_assigned_cargos

        获取被占用的外卖舱  # noqa: E501
        """
        pass

    def test_get_cargo_box(self):
        """Test case for get_cargo_box

        获取Box信息  # noqa: E501
        """
        pass

    def test_get_cargo_boxes(self):
        """Test case for get_cargo_boxes

        获取某个Cargo所有Box信息  # noqa: E501
        """
        pass

    def test_get_cargos(self):
        """Test case for get_cargos

        获取所有Cargo信息  # noqa: E501
        """
        pass

    def test_get_configurations(self):
        """Test case for get_configurations

        获取机器配置信息  # noqa: E501
        """
        pass

    def test_get_delivery_settings(self):
        """Test case for get_delivery_settings

        获取配送相关的设置信息  # noqa: E501
        """
        pass

    def test_get_language(self):
        """Test case for get_language

        获取机器人语言  # noqa: E501
        """
        pass

    def test_get_line_speed(self):
        """Test case for get_line_speed

        获取配送速度和返航速度  # noqa: E501
        """
        pass

    def test_get_move_options(self):
        """Test case for get_move_options

        获取运动选项  # noqa: E501
        """
        pass

    def test_get_operation_result(self):
        """Test case for get_operation_result

        查询Box操作结果  # noqa: E501
        """
        pass

    def test_get_password(self):
        """Test case for get_password

        获取操作密码  # noqa: E501
        """
        pass

    def test_get_stage(self):
        """Test case for get_stage

        获取当前任务状态  # noqa: E501
        """
        pass

    def test_get_tasks(self):
        """Test case for get_tasks

        查询任务信息  # noqa: E501
        """
        pass

    def test_get_voice_resources(self):
        """Test case for get_voice_resources

        获取语音包信息  # noqa: E501
        """
        pass

    def test_get_work_mode(self):
        """Test case for get_work_mode

        获取机器人工作模式  # noqa: E501
        """
        pass

    def test_get_working_time(self):
        """Test case for get_working_time

        获取机器人工作时间  # noqa: E501
        """
        pass

    def test_operate_box(self):
        """Test case for operate_box

        操作Box  # noqa: E501
        """
        pass

    def test_set_language(self):
        """Test case for set_language

        设置机器人语言  # noqa: E501
        """
        pass

    def test_set_line_speed(self):
        """Test case for set_line_speed

        设置配送速度和返航速度  # noqa: E501
        """
        pass

    def test_set_move_options(self):
        """Test case for set_move_options

        设置运动选项  # noqa: E501
        """
        pass

    def test_set_password(self):
        """Test case for set_password

        设置操作密码  # noqa: E501
        """
        pass

    def test_set_task_execution(self):
        """Test case for set_task_execution

        暂停/继续执行任务  # noqa: E501
        """
        pass

    def test_set_timeout_settings(self):
        """Test case for set_timeout_settings

        设置任务的超时时间  # noqa: E501
        """
        pass

    def test_set_work_mode(self):
        """Test case for set_work_mode

        设置机器人工作模式  # noqa: E501
        """
        pass

    def test_set_working_time(self):
        """Test case for set_working_time

        设置机器人工作时间  # noqa: E501
        """
        pass

    def test_start_pickup(self):
        """Test case for start_pickup

        开始取物  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
