# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apicoreartifactv1rectangleareasusageArea(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'Point',
        'end': 'Point',
        'half_width': 'float'
    }

    attribute_map = {
        'start': 'start',
        'end': 'end',
        'half_width': 'half_width'
    }

    def __init__(self, start=None, end=None, half_width=None):  # noqa: E501
        """Apicoreartifactv1rectangleareasusageArea - a model defined in Swagger"""  # noqa: E501
        self._start = None
        self._end = None
        self._half_width = None
        self.discriminator = None
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end
        if half_width is not None:
            self.half_width = half_width

    @property
    def start(self):
        """Gets the start of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501


        :return: The start of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501
        :rtype: Point
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this Apicoreartifactv1rectangleareasusageArea.


        :param start: The start of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501
        :type: Point
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501


        :return: The end of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501
        :rtype: Point
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Apicoreartifactv1rectangleareasusageArea.


        :param end: The end of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501
        :type: Point
        """

        self._end = end

    @property
    def half_width(self):
        """Gets the half_width of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501


        :return: The half_width of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501
        :rtype: float
        """
        return self._half_width

    @half_width.setter
    def half_width(self, half_width):
        """Sets the half_width of this Apicoreartifactv1rectangleareasusageArea.


        :param half_width: The half_width of this Apicoreartifactv1rectangleareasusageArea.  # noqa: E501
        :type: float
        """

        self._half_width = half_width

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apicoreartifactv1rectangleareasusageArea, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apicoreartifactv1rectangleareasusageArea):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
