# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BackOffFromTagActionOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'backup_mode': 'int',
        'tag_type': 'int',
        'backup_distance': 'float',
        'backward_docking': 'bool'
    }

    attribute_map = {
        'backup_mode': 'backup_mode',
        'tag_type': 'tag_type',
        'backup_distance': 'backup_distance',
        'backward_docking': 'backward_docking'
    }

    def __init__(self, backup_mode=None, tag_type=Tag_typeEnum._0, backup_distance=None, backward_docking=False):  # noqa: E501
        """BackOffFromTagActionOptions - a model defined in Swagger"""  # noqa: E501
        self._backup_mode = None
        self._tag_type = None
        self._backup_distance = None
        self._backward_docking = None
        self.discriminator = None
        if backup_mode is not None:
            self.backup_mode = backup_mode
        if tag_type is not None:
            self.tag_type = tag_type
        if backup_distance is not None:
            self.backup_distance = backup_distance
        if backward_docking is not None:
            self.backward_docking = backward_docking

    @property
    def backup_mode(self):
        """Gets the backup_mode of this BackOffFromTagActionOptions.  # noqa: E501

        * `0` 自由后退 * `1` 窄道后退，在后退过程中一直观测二维码并调整角度   # noqa: E501

        :return: The backup_mode of this BackOffFromTagActionOptions.  # noqa: E501
        :rtype: int
        """
        return self._backup_mode

    @backup_mode.setter
    def backup_mode(self, backup_mode):
        """Sets the backup_mode of this BackOffFromTagActionOptions.

        * `0` 自由后退 * `1` 窄道后退，在后退过程中一直观测二维码并调整角度   # noqa: E501

        :param backup_mode: The backup_mode of this BackOffFromTagActionOptions.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1]  # noqa: E501
        if backup_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `backup_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(backup_mode, allowed_values)
            )

        self._backup_mode = backup_mode

    @property
    def tag_type(self):
        """Gets the tag_type of this BackOffFromTagActionOptions.  # noqa: E501

        0：二维码视觉标签， 1：激光标签, 2： 激光反光板  # noqa: E501

        :return: The tag_type of this BackOffFromTagActionOptions.  # noqa: E501
        :rtype: int
        """
        return self._tag_type

    @tag_type.setter
    def tag_type(self, tag_type):
        """Sets the tag_type of this BackOffFromTagActionOptions.

        0：二维码视觉标签， 1：激光标签, 2： 激光反光板  # noqa: E501

        :param tag_type: The tag_type of this BackOffFromTagActionOptions.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1, 2]  # noqa: E501
        if tag_type not in allowed_values:
            raise ValueError(
                "Invalid value for `tag_type` ({0}), must be one of {1}"  # noqa: E501
                .format(tag_type, allowed_values)
            )

        self._tag_type = tag_type

    @property
    def backup_distance(self):
        """Gets the backup_distance of this BackOffFromTagActionOptions.  # noqa: E501

        后退的距离, 可选值，默认后退直到机器可以转身  # noqa: E501

        :return: The backup_distance of this BackOffFromTagActionOptions.  # noqa: E501
        :rtype: float
        """
        return self._backup_distance

    @backup_distance.setter
    def backup_distance(self, backup_distance):
        """Sets the backup_distance of this BackOffFromTagActionOptions.

        后退的距离, 可选值，默认后退直到机器可以转身  # noqa: E501

        :param backup_distance: The backup_distance of this BackOffFromTagActionOptions.  # noqa: E501
        :type: float
        """

        self._backup_distance = backup_distance

    @property
    def backward_docking(self):
        """Gets the backward_docking of this BackOffFromTagActionOptions.  # noqa: E501

        是否向后对接, 如果是向后对接，则调用BackOffFromTagAction时实际是向前移动  # noqa: E501

        :return: The backward_docking of this BackOffFromTagActionOptions.  # noqa: E501
        :rtype: bool
        """
        return self._backward_docking

    @backward_docking.setter
    def backward_docking(self, backward_docking):
        """Sets the backward_docking of this BackOffFromTagActionOptions.

        是否向后对接, 如果是向后对接，则调用BackOffFromTagAction时实际是向前移动  # noqa: E501

        :param backward_docking: The backward_docking of this BackOffFromTagActionOptions.  # noqa: E501
        :type: bool
        """

        self._backward_docking = backward_docking

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BackOffFromTagActionOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BackOffFromTagActionOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
