# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BezierCurveMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'control_point1': 'str',
        'control_point2': 'str'
    }

    attribute_map = {
        'control_point1': 'control_point1',
        'control_point2': 'control_point2'
    }

    def __init__(self, control_point1=None, control_point2=None):  # noqa: E501
        """BezierCurveMetadata - a model defined in Swagger"""  # noqa: E501
        self._control_point1 = None
        self._control_point2 = None
        self.discriminator = None
        self.control_point1 = control_point1
        self.control_point2 = control_point2

    @property
    def control_point1(self):
        """Gets the control_point1 of this BezierCurveMetadata.  # noqa: E501


        :return: The control_point1 of this BezierCurveMetadata.  # noqa: E501
        :rtype: str
        """
        return self._control_point1

    @control_point1.setter
    def control_point1(self, control_point1):
        """Sets the control_point1 of this BezierCurveMetadata.


        :param control_point1: The control_point1 of this BezierCurveMetadata.  # noqa: E501
        :type: str
        """
        if control_point1 is None:
            raise ValueError("Invalid value for `control_point1`, must not be `None`")  # noqa: E501

        self._control_point1 = control_point1

    @property
    def control_point2(self):
        """Gets the control_point2 of this BezierCurveMetadata.  # noqa: E501


        :return: The control_point2 of this BezierCurveMetadata.  # noqa: E501
        :rtype: str
        """
        return self._control_point2

    @control_point2.setter
    def control_point2(self, control_point2):
        """Sets the control_point2 of this BezierCurveMetadata.


        :param control_point2: The control_point2 of this BezierCurveMetadata.  # noqa: E501
        :type: str
        """
        if control_point2 is None:
            raise ValueError("Invalid value for `control_point2`, must not be `None`")  # noqa: E501

        self._control_point2 = control_point2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BezierCurveMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BezierCurveMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
