# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Capability(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'version': 'str',
        'enabled': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'version': 'version',
        'enabled': 'enabled'
    }

    def __init__(self, name=None, version=None, enabled=None):  # noqa: E501
        """Capability - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._version = None
        self._enabled = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version
        if enabled is not None:
            self.enabled = enabled

    @property
    def name(self):
        """Gets the name of this Capability.  # noqa: E501

        * `slamware.agent.core` 定位导航等底盘核心通用功能 * `slamware.agent.platform` 日志采集等平台通用功能 * `slamware.agent.multi_floor` 多楼层地图管理和跨楼层移动功能 * `slamware.agent.delivery` 配送服务功能 * `slamware.agent.mercury2` 支持云端调度的智能酒店配送服务功能   # noqa: E501

        :return: The name of this Capability.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Capability.

        * `slamware.agent.core` 定位导航等底盘核心通用功能 * `slamware.agent.platform` 日志采集等平台通用功能 * `slamware.agent.multi_floor` 多楼层地图管理和跨楼层移动功能 * `slamware.agent.delivery` 配送服务功能 * `slamware.agent.mercury2` 支持云端调度的智能酒店配送服务功能   # noqa: E501

        :param name: The name of this Capability.  # noqa: E501
        :type: str
        """
        allowed_values = ["slamware.agent.core", "slamware.agent.platform", "slamware.agent.multi_floor", "slamware.agent.delivery", "slamware.agent.mercury2"]  # noqa: E501
        if name not in allowed_values:
            raise ValueError(
                "Invalid value for `name` ({0}), must be one of {1}"  # noqa: E501
                .format(name, allowed_values)
            )

        self._name = name

    @property
    def version(self):
        """Gets the version of this Capability.  # noqa: E501


        :return: The version of this Capability.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Capability.


        :param version: The version of this Capability.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def enabled(self):
        """Gets the enabled of this Capability.  # noqa: E501

        插件初始化失败，或者刚启动时该值为false，上位机应当继续等待一段时间，直到该值变成true或者超时。  # noqa: E501

        :return: The enabled of this Capability.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this Capability.

        插件初始化失败，或者刚启动时该值为false，上位机应当继续等待一段时间，直到该值变成true或者超时。  # noqa: E501

        :param enabled: The enabled of this Capability.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Capability, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Capability):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
