# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Cargo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'pos': 'int',
        'orientation': 'str',
        'layer': 'int',
        'type': 'str',
        'errors': 'list[str]',
        'boxes': 'list[Box]'
    }

    attribute_map = {
        'id': 'id',
        'pos': 'pos',
        'orientation': 'orientation',
        'layer': 'layer',
        'type': 'type',
        'errors': 'errors',
        'boxes': 'boxes'
    }

    def __init__(self, id=None, pos=None, orientation=None, layer=None, type=None, errors=None, boxes=None):  # noqa: E501
        """Cargo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._pos = None
        self._orientation = None
        self._layer = None
        self._type = None
        self._errors = None
        self._boxes = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if pos is not None:
            self.pos = pos
        if orientation is not None:
            self.orientation = orientation
        if layer is not None:
            self.layer = layer
        if type is not None:
            self.type = type
        if errors is not None:
            self.errors = errors
        if boxes is not None:
            self.boxes = boxes

    @property
    def id(self):
        """Gets the id of this Cargo.  # noqa: E501


        :return: The id of this Cargo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Cargo.


        :param id: The id of this Cargo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def pos(self):
        """Gets the pos of this Cargo.  # noqa: E501


        :return: The pos of this Cargo.  # noqa: E501
        :rtype: int
        """
        return self._pos

    @pos.setter
    def pos(self, pos):
        """Sets the pos of this Cargo.


        :param pos: The pos of this Cargo.  # noqa: E501
        :type: int
        """

        self._pos = pos

    @property
    def orientation(self):
        """Gets the orientation of this Cargo.  # noqa: E501


        :return: The orientation of this Cargo.  # noqa: E501
        :rtype: str
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation):
        """Sets the orientation of this Cargo.


        :param orientation: The orientation of this Cargo.  # noqa: E501
        :type: str
        """
        allowed_values = ["FRONT", "BACK", "TOP"]  # noqa: E501
        if orientation not in allowed_values:
            raise ValueError(
                "Invalid value for `orientation` ({0}), must be one of {1}"  # noqa: E501
                .format(orientation, allowed_values)
            )

        self._orientation = orientation

    @property
    def layer(self):
        """Gets the layer of this Cargo.  # noqa: E501


        :return: The layer of this Cargo.  # noqa: E501
        :rtype: int
        """
        return self._layer

    @layer.setter
    def layer(self, layer):
        """Sets the layer of this Cargo.


        :param layer: The layer of this Cargo.  # noqa: E501
        :type: int
        """

        self._layer = layer

    @property
    def type(self):
        """Gets the type of this Cargo.  # noqa: E501


        :return: The type of this Cargo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Cargo.


        :param type: The type of this Cargo.  # noqa: E501
        :type: str
        """
        allowed_values = ["TAKEOUT", "RETAIL"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def errors(self):
        """Gets the errors of this Cargo.  # noqa: E501


        :return: The errors of this Cargo.  # noqa: E501
        :rtype: list[str]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this Cargo.


        :param errors: The errors of this Cargo.  # noqa: E501
        :type: list[str]
        """

        self._errors = errors

    @property
    def boxes(self):
        """Gets the boxes of this Cargo.  # noqa: E501


        :return: The boxes of this Cargo.  # noqa: E501
        :rtype: list[Box]
        """
        return self._boxes

    @boxes.setter
    def boxes(self, boxes):
        """Sets the boxes of this Cargo.


        :param boxes: The boxes of this Cargo.  # noqa: E501
        :type: list[Box]
        """

        self._boxes = boxes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Cargo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Cargo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
