# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CurrentFloorInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'building': 'str',
        'floor': 'str',
        'elevator': 'str',
        'map_id': 'str'
    }

    attribute_map = {
        'building': 'building',
        'floor': 'floor',
        'elevator': 'elevator',
        'map_id': 'map_id'
    }

    def __init__(self, building='', floor=None, elevator='', map_id=None):  # noqa: E501
        """CurrentFloorInfo - a model defined in Swagger"""  # noqa: E501
        self._building = None
        self._floor = None
        self._elevator = None
        self._map_id = None
        self.discriminator = None
        if building is not None:
            self.building = building
        if floor is not None:
            self.floor = floor
        if elevator is not None:
            self.elevator = elevator
        if map_id is not None:
            self.map_id = map_id

    @property
    def building(self):
        """Gets the building of this CurrentFloorInfo.  # noqa: E501


        :return: The building of this CurrentFloorInfo.  # noqa: E501
        :rtype: str
        """
        return self._building

    @building.setter
    def building(self, building):
        """Sets the building of this CurrentFloorInfo.


        :param building: The building of this CurrentFloorInfo.  # noqa: E501
        :type: str
        """

        self._building = building

    @property
    def floor(self):
        """Gets the floor of this CurrentFloorInfo.  # noqa: E501


        :return: The floor of this CurrentFloorInfo.  # noqa: E501
        :rtype: str
        """
        return self._floor

    @floor.setter
    def floor(self, floor):
        """Sets the floor of this CurrentFloorInfo.


        :param floor: The floor of this CurrentFloorInfo.  # noqa: E501
        :type: str
        """

        self._floor = floor

    @property
    def elevator(self):
        """Gets the elevator of this CurrentFloorInfo.  # noqa: E501

        如果该字段非空则表示机器人还在电梯内。  # noqa: E501

        :return: The elevator of this CurrentFloorInfo.  # noqa: E501
        :rtype: str
        """
        return self._elevator

    @elevator.setter
    def elevator(self, elevator):
        """Sets the elevator of this CurrentFloorInfo.

        如果该字段非空则表示机器人还在电梯内。  # noqa: E501

        :param elevator: The elevator of this CurrentFloorInfo.  # noqa: E501
        :type: str
        """

        self._elevator = elevator

    @property
    def map_id(self):
        """Gets the map_id of this CurrentFloorInfo.  # noqa: E501

        当前所在楼层的地图ID  # noqa: E501

        :return: The map_id of this CurrentFloorInfo.  # noqa: E501
        :rtype: str
        """
        return self._map_id

    @map_id.setter
    def map_id(self, map_id):
        """Sets the map_id of this CurrentFloorInfo.

        当前所在楼层的地图ID  # noqa: E501

        :param map_id: The map_id of this CurrentFloorInfo.  # noqa: E501
        :type: str
        """

        self._map_id = map_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CurrentFloorInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CurrentFloorInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
