# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DangerousAreaMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dangerous_area_type': 'str',
        'max_line_speed': 'str'
    }

    attribute_map = {
        'dangerous_area_type': 'dangerous_area_type',
        'max_line_speed': 'max_line_speed'
    }

    def __init__(self, dangerous_area_type=None, max_line_speed=None):  # noqa: E501
        """DangerousAreaMetadata - a model defined in Swagger"""  # noqa: E501
        self._dangerous_area_type = None
        self._max_line_speed = None
        self.discriminator = None
        self.dangerous_area_type = dangerous_area_type
        if max_line_speed is not None:
            self.max_line_speed = max_line_speed

    @property
    def dangerous_area_type(self):
        """Gets the dangerous_area_type of this DangerousAreaMetadata.  # noqa: E501

        危险区域类型, 0 斜坡，1 窄走廊  # noqa: E501

        :return: The dangerous_area_type of this DangerousAreaMetadata.  # noqa: E501
        :rtype: str
        """
        return self._dangerous_area_type

    @dangerous_area_type.setter
    def dangerous_area_type(self, dangerous_area_type):
        """Sets the dangerous_area_type of this DangerousAreaMetadata.

        危险区域类型, 0 斜坡，1 窄走廊  # noqa: E501

        :param dangerous_area_type: The dangerous_area_type of this DangerousAreaMetadata.  # noqa: E501
        :type: str
        """
        if dangerous_area_type is None:
            raise ValueError("Invalid value for `dangerous_area_type`, must not be `None`")  # noqa: E501
        allowed_values = ["0", "1"]  # noqa: E501
        if dangerous_area_type not in allowed_values:
            raise ValueError(
                "Invalid value for `dangerous_area_type` ({0}), must be one of {1}"  # noqa: E501
                .format(dangerous_area_type, allowed_values)
            )

        self._dangerous_area_type = dangerous_area_type

    @property
    def max_line_speed(self):
        """Gets the max_line_speed of this DangerousAreaMetadata.  # noqa: E501

        机器人在该区域内的最大线速度, 单位米/秒  # noqa: E501

        :return: The max_line_speed of this DangerousAreaMetadata.  # noqa: E501
        :rtype: str
        """
        return self._max_line_speed

    @max_line_speed.setter
    def max_line_speed(self, max_line_speed):
        """Sets the max_line_speed of this DangerousAreaMetadata.

        机器人在该区域内的最大线速度, 单位米/秒  # noqa: E501

        :param max_line_speed: The max_line_speed of this DangerousAreaMetadata.  # noqa: E501
        :type: str
        """

        self._max_line_speed = max_line_speed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DangerousAreaMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DangerousAreaMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
