# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryTaskRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target': 'str',
        'type': 'str',
        'req_id': 'str',
        'order_id': 'str',
        'no_pickup_wait': 'bool',
        'cargos': 'list[CargoEntry]',
        'failed_tasks': 'list[FailedTask]',
        'station_id': 'str',
        'station_cargos': 'list[CargoEntry]',
        'message': 'object'
    }

    attribute_map = {
        'target': 'target',
        'type': 'type',
        'req_id': 'req_id',
        'order_id': 'order_id',
        'no_pickup_wait': 'no_pickup_wait',
        'cargos': 'cargos',
        'failed_tasks': 'failed_tasks',
        'station_id': 'station_id',
        'station_cargos': 'station_cargos',
        'message': 'message'
    }

    def __init__(self, target=None, type=None, req_id=None, order_id=None, no_pickup_wait=None, cargos=None, failed_tasks=None, station_id=None, station_cargos=None, message=None):  # noqa: E501
        """DeliveryTaskRequest - a model defined in Swagger"""  # noqa: E501
        self._target = None
        self._type = None
        self._req_id = None
        self._order_id = None
        self._no_pickup_wait = None
        self._cargos = None
        self._failed_tasks = None
        self._station_id = None
        self._station_cargos = None
        self._message = None
        self.discriminator = None
        if target is not None:
            self.target = target
        if type is not None:
            self.type = type
        if req_id is not None:
            self.req_id = req_id
        if order_id is not None:
            self.order_id = order_id
        if no_pickup_wait is not None:
            self.no_pickup_wait = no_pickup_wait
        if cargos is not None:
            self.cargos = cargos
        if failed_tasks is not None:
            self.failed_tasks = failed_tasks
        if station_id is not None:
            self.station_id = station_id
        if station_cargos is not None:
            self.station_cargos = station_cargos
        if message is not None:
            self.message = message

    @property
    def target(self):
        """Gets the target of this DeliveryTaskRequest.  # noqa: E501


        :return: The target of this DeliveryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this DeliveryTaskRequest.


        :param target: The target of this DeliveryTaskRequest.  # noqa: E501
        :type: str
        """

        self._target = target

    @property
    def type(self):
        """Gets the type of this DeliveryTaskRequest.  # noqa: E501


        :return: The type of this DeliveryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DeliveryTaskRequest.


        :param type: The type of this DeliveryTaskRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["REFILL", "COLLECT", "TAKEOUT", "RETAIL", "STATION_TAKEOUT", "GUIDE", "FOOD_DELIVERY", "RETURN", "RECYCLE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def req_id(self):
        """Gets the req_id of this DeliveryTaskRequest.  # noqa: E501


        :return: The req_id of this DeliveryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._req_id

    @req_id.setter
    def req_id(self, req_id):
        """Sets the req_id of this DeliveryTaskRequest.


        :param req_id: The req_id of this DeliveryTaskRequest.  # noqa: E501
        :type: str
        """

        self._req_id = req_id

    @property
    def order_id(self):
        """Gets the order_id of this DeliveryTaskRequest.  # noqa: E501


        :return: The order_id of this DeliveryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this DeliveryTaskRequest.


        :param order_id: The order_id of this DeliveryTaskRequest.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def no_pickup_wait(self):
        """Gets the no_pickup_wait of this DeliveryTaskRequest.  # noqa: E501


        :return: The no_pickup_wait of this DeliveryTaskRequest.  # noqa: E501
        :rtype: bool
        """
        return self._no_pickup_wait

    @no_pickup_wait.setter
    def no_pickup_wait(self, no_pickup_wait):
        """Sets the no_pickup_wait of this DeliveryTaskRequest.


        :param no_pickup_wait: The no_pickup_wait of this DeliveryTaskRequest.  # noqa: E501
        :type: bool
        """

        self._no_pickup_wait = no_pickup_wait

    @property
    def cargos(self):
        """Gets the cargos of this DeliveryTaskRequest.  # noqa: E501


        :return: The cargos of this DeliveryTaskRequest.  # noqa: E501
        :rtype: list[CargoEntry]
        """
        return self._cargos

    @cargos.setter
    def cargos(self, cargos):
        """Sets the cargos of this DeliveryTaskRequest.


        :param cargos: The cargos of this DeliveryTaskRequest.  # noqa: E501
        :type: list[CargoEntry]
        """

        self._cargos = cargos

    @property
    def failed_tasks(self):
        """Gets the failed_tasks of this DeliveryTaskRequest.  # noqa: E501


        :return: The failed_tasks of this DeliveryTaskRequest.  # noqa: E501
        :rtype: list[FailedTask]
        """
        return self._failed_tasks

    @failed_tasks.setter
    def failed_tasks(self, failed_tasks):
        """Sets the failed_tasks of this DeliveryTaskRequest.


        :param failed_tasks: The failed_tasks of this DeliveryTaskRequest.  # noqa: E501
        :type: list[FailedTask]
        """

        self._failed_tasks = failed_tasks

    @property
    def station_id(self):
        """Gets the station_id of this DeliveryTaskRequest.  # noqa: E501


        :return: The station_id of this DeliveryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._station_id

    @station_id.setter
    def station_id(self, station_id):
        """Sets the station_id of this DeliveryTaskRequest.


        :param station_id: The station_id of this DeliveryTaskRequest.  # noqa: E501
        :type: str
        """

        self._station_id = station_id

    @property
    def station_cargos(self):
        """Gets the station_cargos of this DeliveryTaskRequest.  # noqa: E501


        :return: The station_cargos of this DeliveryTaskRequest.  # noqa: E501
        :rtype: list[CargoEntry]
        """
        return self._station_cargos

    @station_cargos.setter
    def station_cargos(self, station_cargos):
        """Sets the station_cargos of this DeliveryTaskRequest.


        :param station_cargos: The station_cargos of this DeliveryTaskRequest.  # noqa: E501
        :type: list[CargoEntry]
        """

        self._station_cargos = station_cargos

    @property
    def message(self):
        """Gets the message of this DeliveryTaskRequest.  # noqa: E501


        :return: The message of this DeliveryTaskRequest.  # noqa: E501
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DeliveryTaskRequest.


        :param message: The message of this DeliveryTaskRequest.  # noqa: E501
        :type: object
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryTaskRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryTaskRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
