# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliverySettingsLowBatteryLevel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'level1': 'int',
        'level2': 'int',
        'level3': 'int',
        'level4': 'int'
    }

    attribute_map = {
        'level1': 'level1',
        'level2': 'level2',
        'level3': 'level3',
        'level4': 'level4'
    }

    def __init__(self, level1=6, level2=10, level3=20, level4=30):  # noqa: E501
        """DeliverySettingsLowBatteryLevel - a model defined in Swagger"""  # noqa: E501
        self._level1 = None
        self._level2 = None
        self._level3 = None
        self._level4 = None
        self.discriminator = None
        if level1 is not None:
            self.level1 = level1
        if level2 is not None:
            self.level2 = level2
        if level3 is not None:
            self.level3 = level3
        if level4 is not None:
            self.level4 = level4

    @property
    def level1(self):
        """Gets the level1 of this DeliverySettingsLowBatteryLevel.  # noqa: E501

        达到该电量时机器人自动关机  # noqa: E501

        :return: The level1 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :rtype: int
        """
        return self._level1

    @level1.setter
    def level1(self, level1):
        """Sets the level1 of this DeliverySettingsLowBatteryLevel.

        达到该电量时机器人自动关机  # noqa: E501

        :param level1: The level1 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :type: int
        """

        self._level1 = level1

    @property
    def level2(self):
        """Gets the level2 of this DeliverySettingsLowBatteryLevel.  # noqa: E501

        达到该电量时机器人取消所有任务并回桩  # noqa: E501

        :return: The level2 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :rtype: int
        """
        return self._level2

    @level2.setter
    def level2(self, level2):
        """Sets the level2 of this DeliverySettingsLowBatteryLevel.

        达到该电量时机器人取消所有任务并回桩  # noqa: E501

        :param level2: The level2 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :type: int
        """

        self._level2 = level2

    @property
    def level3(self):
        """Gets the level3 of this DeliverySettingsLowBatteryLevel.  # noqa: E501

        预留，通过云端调度机器时，一旦达到该电量应当禁止下发新的任务  # noqa: E501

        :return: The level3 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :rtype: int
        """
        return self._level3

    @level3.setter
    def level3(self, level3):
        """Sets the level3 of this DeliverySettingsLowBatteryLevel.

        预留，通过云端调度机器时，一旦达到该电量应当禁止下发新的任务  # noqa: E501

        :param level3: The level3 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :type: int
        """

        self._level3 = level3

    @property
    def level4(self):
        """Gets the level4 of this DeliverySettingsLowBatteryLevel.  # noqa: E501

        达到该电量时，机器人无法创建外卖配送单  # noqa: E501

        :return: The level4 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :rtype: int
        """
        return self._level4

    @level4.setter
    def level4(self, level4):
        """Sets the level4 of this DeliverySettingsLowBatteryLevel.

        达到该电量时，机器人无法创建外卖配送单  # noqa: E501

        :param level4: The level4 of this DeliverySettingsLowBatteryLevel.  # noqa: E501
        :type: int
        """

        self._level4 = level4

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliverySettingsLowBatteryLevel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliverySettingsLowBatteryLevel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
