# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeliveryEventType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    START_FROM_DOCK = "START_FROM_DOCK"
    DELIVERY_SETTINGS_CHANGED = "DELIVERY_SETTINGS_CHANGED"
    DELIVERY_TASK_START = "DELIVERY_TASK_START"
    STATION_TASK_START = "STATION_TASK_START"
    OPERATING_CABINET = "OPERATING_CABINET"
    BACK_TO_RECEPTION_FOR_FAILED_ORDER = "BACK_TO_RECEPTION_FOR_FAILED_ORDER"
    DELIVERY_NO_PICKUP = "DELIVERY_NO_PICKUP"
    COLLECT_NO_PICKUP = "COLLECT_NO_PICKUP"
    UNDOCK_FAILED = "UNDOCK_FAILED"
    START_TO_WORK = "START_TO_WORK"
    GET_OFF_WORK = "GET_OFF_WORK"
    LOW_BATTERY = "LOW_BATTERY"
    NEW_TASK_RECEIVED = "NEW_TASK_RECEIVED"
    ROBOT_REBOOT = "ROBOT_REBOOT"
    DISINFECT_TASK_FAILED = "DISINFECT_TASK_FAILED"
    LOCALIZATION_ANOMALY = "LOCALIZATION_ANOMALY"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """DeliveryEventType - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeliveryEventType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeliveryEventType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
