# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeviceInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'manufacturer_id': 'int',
        'manufacturer_name': 'str',
        'model_id': 'int',
        'model_name': 'str',
        'device_id': 'str',
        'hardware_version': 'str',
        'software_version': 'str'
    }

    attribute_map = {
        'manufacturer_id': 'manufacturerId',
        'manufacturer_name': 'manufacturerName',
        'model_id': 'modelId',
        'model_name': 'modelName',
        'device_id': 'deviceID',
        'hardware_version': 'hardwareVersion',
        'software_version': 'softwareVersion'
    }

    def __init__(self, manufacturer_id=None, manufacturer_name=None, model_id=None, model_name=None, device_id=None, hardware_version=None, software_version=None):  # noqa: E501
        """DeviceInfo - a model defined in Swagger"""  # noqa: E501
        self._manufacturer_id = None
        self._manufacturer_name = None
        self._model_id = None
        self._model_name = None
        self._device_id = None
        self._hardware_version = None
        self._software_version = None
        self.discriminator = None
        if manufacturer_id is not None:
            self.manufacturer_id = manufacturer_id
        if manufacturer_name is not None:
            self.manufacturer_name = manufacturer_name
        if model_id is not None:
            self.model_id = model_id
        if model_name is not None:
            self.model_name = model_name
        if device_id is not None:
            self.device_id = device_id
        if hardware_version is not None:
            self.hardware_version = hardware_version
        if software_version is not None:
            self.software_version = software_version

    @property
    def manufacturer_id(self):
        """Gets the manufacturer_id of this DeviceInfo.  # noqa: E501

        制造商ID  # noqa: E501

        :return: The manufacturer_id of this DeviceInfo.  # noqa: E501
        :rtype: int
        """
        return self._manufacturer_id

    @manufacturer_id.setter
    def manufacturer_id(self, manufacturer_id):
        """Sets the manufacturer_id of this DeviceInfo.

        制造商ID  # noqa: E501

        :param manufacturer_id: The manufacturer_id of this DeviceInfo.  # noqa: E501
        :type: int
        """

        self._manufacturer_id = manufacturer_id

    @property
    def manufacturer_name(self):
        """Gets the manufacturer_name of this DeviceInfo.  # noqa: E501

        制造商名称  # noqa: E501

        :return: The manufacturer_name of this DeviceInfo.  # noqa: E501
        :rtype: str
        """
        return self._manufacturer_name

    @manufacturer_name.setter
    def manufacturer_name(self, manufacturer_name):
        """Sets the manufacturer_name of this DeviceInfo.

        制造商名称  # noqa: E501

        :param manufacturer_name: The manufacturer_name of this DeviceInfo.  # noqa: E501
        :type: str
        """

        self._manufacturer_name = manufacturer_name

    @property
    def model_id(self):
        """Gets the model_id of this DeviceInfo.  # noqa: E501

        设备型号ID  # noqa: E501

        :return: The model_id of this DeviceInfo.  # noqa: E501
        :rtype: int
        """
        return self._model_id

    @model_id.setter
    def model_id(self, model_id):
        """Sets the model_id of this DeviceInfo.

        设备型号ID  # noqa: E501

        :param model_id: The model_id of this DeviceInfo.  # noqa: E501
        :type: int
        """

        self._model_id = model_id

    @property
    def model_name(self):
        """Gets the model_name of this DeviceInfo.  # noqa: E501

        设备型号名称  # noqa: E501

        :return: The model_name of this DeviceInfo.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this DeviceInfo.

        设备型号名称  # noqa: E501

        :param model_name: The model_name of this DeviceInfo.  # noqa: E501
        :type: str
        """

        self._model_name = model_name

    @property
    def device_id(self):
        """Gets the device_id of this DeviceInfo.  # noqa: E501

        设备序列号  # noqa: E501

        :return: The device_id of this DeviceInfo.  # noqa: E501
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this DeviceInfo.

        设备序列号  # noqa: E501

        :param device_id: The device_id of this DeviceInfo.  # noqa: E501
        :type: str
        """

        self._device_id = device_id

    @property
    def hardware_version(self):
        """Gets the hardware_version of this DeviceInfo.  # noqa: E501

        硬件版本号  # noqa: E501

        :return: The hardware_version of this DeviceInfo.  # noqa: E501
        :rtype: str
        """
        return self._hardware_version

    @hardware_version.setter
    def hardware_version(self, hardware_version):
        """Sets the hardware_version of this DeviceInfo.

        硬件版本号  # noqa: E501

        :param hardware_version: The hardware_version of this DeviceInfo.  # noqa: E501
        :type: str
        """

        self._hardware_version = hardware_version

    @property
    def software_version(self):
        """Gets the software_version of this DeviceInfo.  # noqa: E501

        软件版本号  # noqa: E501

        :return: The software_version of this DeviceInfo.  # noqa: E501
        :rtype: str
        """
        return self._software_version

    @software_version.setter
    def software_version(self, software_version):
        """Sets the software_version of this DeviceInfo.

        软件版本号  # noqa: E501

        :param software_version: The software_version of this DeviceInfo.  # noqa: E501
        :type: str
        """

        self._software_version = software_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
