# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeviceError(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'component': 'int',
        'error_code': 'int',
        'error_level': 'int',
        'message': 'str'
    }

    attribute_map = {
        'component': 'component',
        'error_code': 'error_code',
        'error_level': 'error_level',
        'message': 'message'
    }

    def __init__(self, component=None, error_code=None, error_level=None, message=None):  # noqa: E501
        """DeviceError - a model defined in Swagger"""  # noqa: E501
        self._component = None
        self._error_code = None
        self._error_level = None
        self._message = None
        self.discriminator = None
        if component is not None:
            self.component = component
        if error_code is not None:
            self.error_code = error_code
        if error_level is not None:
            self.error_level = error_level
        if message is not None:
            self.message = message

    @property
    def component(self):
        """Gets the component of this DeviceError.  # noqa: E501


        :return: The component of this DeviceError.  # noqa: E501
        :rtype: int
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this DeviceError.


        :param component: The component of this DeviceError.  # noqa: E501
        :type: int
        """

        self._component = component

    @property
    def error_code(self):
        """Gets the error_code of this DeviceError.  # noqa: E501


        :return: The error_code of this DeviceError.  # noqa: E501
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code):
        """Sets the error_code of this DeviceError.


        :param error_code: The error_code of this DeviceError.  # noqa: E501
        :type: int
        """

        self._error_code = error_code

    @property
    def error_level(self):
        """Gets the error_level of this DeviceError.  # noqa: E501


        :return: The error_level of this DeviceError.  # noqa: E501
        :rtype: int
        """
        return self._error_level

    @error_level.setter
    def error_level(self, error_level):
        """Sets the error_level of this DeviceError.


        :param error_level: The error_level of this DeviceError.  # noqa: E501
        :type: int
        """

        self._error_level = error_level

    @property
    def message(self):
        """Gets the message of this DeviceError.  # noqa: E501


        :return: The message of this DeviceError.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this DeviceError.


        :param message: The message of this DeviceError.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceError, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceError):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
