# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EnterElevatorOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elevator_door_flag': 'list[str]',
        'elevator_stopping_yaw': 'list[str]',
        'timeout_in_ms': 'float',
        'use_conservative_mode': 'bool'
    }

    attribute_map = {
        'elevator_door_flag': 'elevator_door_flag',
        'elevator_stopping_yaw': 'elevator_stopping_yaw',
        'timeout_in_ms': 'timeout_in_ms',
        'use_conservative_mode': 'use_conservative_mode'
    }

    def __init__(self, elevator_door_flag=None, elevator_stopping_yaw=None, timeout_in_ms=None, use_conservative_mode=None):  # noqa: E501
        """EnterElevatorOptions - a model defined in Swagger"""  # noqa: E501
        self._elevator_door_flag = None
        self._elevator_stopping_yaw = None
        self._timeout_in_ms = None
        self._use_conservative_mode = None
        self.discriminator = None
        if elevator_door_flag is not None:
            self.elevator_door_flag = elevator_door_flag
        if elevator_stopping_yaw is not None:
            self.elevator_stopping_yaw = elevator_stopping_yaw
        if timeout_in_ms is not None:
            self.timeout_in_ms = timeout_in_ms
        if use_conservative_mode is not None:
            self.use_conservative_mode = use_conservative_mode

    @property
    def elevator_door_flag(self):
        """Gets the elevator_door_flag of this EnterElevatorOptions.  # noqa: E501

        * `front_door` 从电梯前门进入 * `rear_door` 从电梯后门进入   # noqa: E501

        :return: The elevator_door_flag of this EnterElevatorOptions.  # noqa: E501
        :rtype: list[str]
        """
        return self._elevator_door_flag

    @elevator_door_flag.setter
    def elevator_door_flag(self, elevator_door_flag):
        """Sets the elevator_door_flag of this EnterElevatorOptions.

        * `front_door` 从电梯前门进入 * `rear_door` 从电梯后门进入   # noqa: E501

        :param elevator_door_flag: The elevator_door_flag of this EnterElevatorOptions.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["front_door", "rear_door"]  # noqa: E501
        if not set(elevator_door_flag).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `elevator_door_flag` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(elevator_door_flag) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._elevator_door_flag = elevator_door_flag

    @property
    def elevator_stopping_yaw(self):
        """Gets the elevator_stopping_yaw of this EnterElevatorOptions.  # noqa: E501

        * `face_to_front_door` 进入电梯后面向电梯前门 * `face_to_rear_door` 进入电梯后面向电梯后门   # noqa: E501

        :return: The elevator_stopping_yaw of this EnterElevatorOptions.  # noqa: E501
        :rtype: list[str]
        """
        return self._elevator_stopping_yaw

    @elevator_stopping_yaw.setter
    def elevator_stopping_yaw(self, elevator_stopping_yaw):
        """Sets the elevator_stopping_yaw of this EnterElevatorOptions.

        * `face_to_front_door` 进入电梯后面向电梯前门 * `face_to_rear_door` 进入电梯后面向电梯后门   # noqa: E501

        :param elevator_stopping_yaw: The elevator_stopping_yaw of this EnterElevatorOptions.  # noqa: E501
        :type: list[str]
        """
        allowed_values = ["face_to_front_door", "face_to_rear_door"]  # noqa: E501
        if not set(elevator_stopping_yaw).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `elevator_stopping_yaw` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(elevator_stopping_yaw) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._elevator_stopping_yaw = elevator_stopping_yaw

    @property
    def timeout_in_ms(self):
        """Gets the timeout_in_ms of this EnterElevatorOptions.  # noqa: E501

        进电梯的总时长  # noqa: E501

        :return: The timeout_in_ms of this EnterElevatorOptions.  # noqa: E501
        :rtype: float
        """
        return self._timeout_in_ms

    @timeout_in_ms.setter
    def timeout_in_ms(self, timeout_in_ms):
        """Sets the timeout_in_ms of this EnterElevatorOptions.

        进电梯的总时长  # noqa: E501

        :param timeout_in_ms: The timeout_in_ms of this EnterElevatorOptions.  # noqa: E501
        :type: float
        """

        self._timeout_in_ms = timeout_in_ms

    @property
    def use_conservative_mode(self):
        """Gets the use_conservative_mode of this EnterElevatorOptions.  # noqa: E501

        true表示保守策略，前往电梯中心点。false表示挤电梯，前往电梯更里面  # noqa: E501

        :return: The use_conservative_mode of this EnterElevatorOptions.  # noqa: E501
        :rtype: bool
        """
        return self._use_conservative_mode

    @use_conservative_mode.setter
    def use_conservative_mode(self, use_conservative_mode):
        """Sets the use_conservative_mode of this EnterElevatorOptions.

        true表示保守策略，前往电梯中心点。false表示挤电梯，前往电梯更里面  # noqa: E501

        :param use_conservative_mode: The use_conservative_mode of this EnterElevatorOptions.  # noqa: E501
        :type: bool
        """

        self._use_conservative_mode = use_conservative_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnterElevatorOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnterElevatorOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
