# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EnterElevatorActionOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elevator_id': 'str',
        'enter_elevator_options': 'EnterElevatorOptions'
    }

    attribute_map = {
        'elevator_id': 'elevator_id',
        'enter_elevator_options': 'enter_elevator_options'
    }

    def __init__(self, elevator_id=None, enter_elevator_options=None):  # noqa: E501
        """EnterElevatorActionOptions - a model defined in Swagger"""  # noqa: E501
        self._elevator_id = None
        self._enter_elevator_options = None
        self.discriminator = None
        self.elevator_id = elevator_id
        if enter_elevator_options is not None:
            self.enter_elevator_options = enter_elevator_options

    @property
    def elevator_id(self):
        """Gets the elevator_id of this EnterElevatorActionOptions.  # noqa: E501


        :return: The elevator_id of this EnterElevatorActionOptions.  # noqa: E501
        :rtype: str
        """
        return self._elevator_id

    @elevator_id.setter
    def elevator_id(self, elevator_id):
        """Sets the elevator_id of this EnterElevatorActionOptions.


        :param elevator_id: The elevator_id of this EnterElevatorActionOptions.  # noqa: E501
        :type: str
        """
        if elevator_id is None:
            raise ValueError("Invalid value for `elevator_id`, must not be `None`")  # noqa: E501

        self._elevator_id = elevator_id

    @property
    def enter_elevator_options(self):
        """Gets the enter_elevator_options of this EnterElevatorActionOptions.  # noqa: E501


        :return: The enter_elevator_options of this EnterElevatorActionOptions.  # noqa: E501
        :rtype: EnterElevatorOptions
        """
        return self._enter_elevator_options

    @enter_elevator_options.setter
    def enter_elevator_options(self, enter_elevator_options):
        """Sets the enter_elevator_options of this EnterElevatorActionOptions.


        :param enter_elevator_options: The enter_elevator_options of this EnterElevatorActionOptions.  # noqa: E501
        :type: EnterElevatorOptions
        """

        self._enter_elevator_options = enter_elevator_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnterElevatorActionOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnterElevatorActionOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
