# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FirmwareInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'manufacturer': 'str',
        'model': 'str',
        'firmware': 'str',
        'firmware_id': 'str'
    }

    attribute_map = {
        'manufacturer': 'manufacturer',
        'model': 'model',
        'firmware': 'firmware',
        'firmware_id': 'firmware_id'
    }

    def __init__(self, manufacturer='Slamtec', model='Hermes', firmware='4.2.2-rtm+20211011', firmware_id=None):  # noqa: E501
        """FirmwareInfo - a model defined in Swagger"""  # noqa: E501
        self._manufacturer = None
        self._model = None
        self._firmware = None
        self._firmware_id = None
        self.discriminator = None
        if manufacturer is not None:
            self.manufacturer = manufacturer
        if model is not None:
            self.model = model
        if firmware is not None:
            self.firmware = firmware
        if firmware_id is not None:
            self.firmware_id = firmware_id

    @property
    def manufacturer(self):
        """Gets the manufacturer of this FirmwareInfo.  # noqa: E501


        :return: The manufacturer of this FirmwareInfo.  # noqa: E501
        :rtype: str
        """
        return self._manufacturer

    @manufacturer.setter
    def manufacturer(self, manufacturer):
        """Sets the manufacturer of this FirmwareInfo.


        :param manufacturer: The manufacturer of this FirmwareInfo.  # noqa: E501
        :type: str
        """

        self._manufacturer = manufacturer

    @property
    def model(self):
        """Gets the model of this FirmwareInfo.  # noqa: E501


        :return: The model of this FirmwareInfo.  # noqa: E501
        :rtype: str
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this FirmwareInfo.


        :param model: The model of this FirmwareInfo.  # noqa: E501
        :type: str
        """

        self._model = model

    @property
    def firmware(self):
        """Gets the firmware of this FirmwareInfo.  # noqa: E501


        :return: The firmware of this FirmwareInfo.  # noqa: E501
        :rtype: str
        """
        return self._firmware

    @firmware.setter
    def firmware(self, firmware):
        """Sets the firmware of this FirmwareInfo.


        :param firmware: The firmware of this FirmwareInfo.  # noqa: E501
        :type: str
        """

        self._firmware = firmware

    @property
    def firmware_id(self):
        """Gets the firmware_id of this FirmwareInfo.  # noqa: E501


        :return: The firmware_id of this FirmwareInfo.  # noqa: E501
        :rtype: str
        """
        return self._firmware_id

    @firmware_id.setter
    def firmware_id(self, firmware_id):
        """Sets the firmware_id of this FirmwareInfo.


        :param firmware_id: The firmware_id of this FirmwareInfo.  # noqa: E501
        :type: str
        """

        self._firmware_id = firmware_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FirmwareInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FirmwareInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
