# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FloorInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'building': 'str',
        'floor': 'str',
        'order': 'int',
        'is_default_floor': 'bool'
    }

    attribute_map = {
        'building': 'building',
        'floor': 'floor',
        'order': 'order',
        'is_default_floor': 'is_default_floor'
    }

    def __init__(self, building='', floor=None, order=None, is_default_floor=None):  # noqa: E501
        """FloorInfo - a model defined in Swagger"""  # noqa: E501
        self._building = None
        self._floor = None
        self._order = None
        self._is_default_floor = None
        self.discriminator = None
        if building is not None:
            self.building = building
        if floor is not None:
            self.floor = floor
        if order is not None:
            self.order = order
        if is_default_floor is not None:
            self.is_default_floor = is_default_floor

    @property
    def building(self):
        """Gets the building of this FloorInfo.  # noqa: E501


        :return: The building of this FloorInfo.  # noqa: E501
        :rtype: str
        """
        return self._building

    @building.setter
    def building(self, building):
        """Sets the building of this FloorInfo.


        :param building: The building of this FloorInfo.  # noqa: E501
        :type: str
        """

        self._building = building

    @property
    def floor(self):
        """Gets the floor of this FloorInfo.  # noqa: E501


        :return: The floor of this FloorInfo.  # noqa: E501
        :rtype: str
        """
        return self._floor

    @floor.setter
    def floor(self, floor):
        """Sets the floor of this FloorInfo.


        :param floor: The floor of this FloorInfo.  # noqa: E501
        :type: str
        """

        self._floor = floor

    @property
    def order(self):
        """Gets the order of this FloorInfo.  # noqa: E501

        如果需要在UI中列出楼层信息，应当按此字段排序  # noqa: E501

        :return: The order of this FloorInfo.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this FloorInfo.

        如果需要在UI中列出楼层信息，应当按此字段排序  # noqa: E501

        :param order: The order of this FloorInfo.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def is_default_floor(self):
        """Gets the is_default_floor of this FloorInfo.  # noqa: E501

        是否为默认楼层，不指定启动楼层时，机器人会设置到默认楼层。所有电梯都需要停靠默认楼层。  # noqa: E501

        :return: The is_default_floor of this FloorInfo.  # noqa: E501
        :rtype: bool
        """
        return self._is_default_floor

    @is_default_floor.setter
    def is_default_floor(self, is_default_floor):
        """Sets the is_default_floor of this FloorInfo.

        是否为默认楼层，不指定启动楼层时，机器人会设置到默认楼层。所有电梯都需要停靠默认楼层。  # noqa: E501

        :param is_default_floor: The is_default_floor of this FloorInfo.  # noqa: E501
        :type: bool
        """

        self._is_default_floor = is_default_floor

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FloorInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FloorInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
