# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GoHomeActionOptionsGohomeOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flags': 'str',
        'back_to_landing': 'bool',
        'charging_retry_count': 'int',
        'move_options': 'GoHomeActionOptionsGohomeOptionsMoveOptions'
    }

    attribute_map = {
        'flags': 'flags',
        'back_to_landing': 'back_to_landing',
        'charging_retry_count': 'charging_retry_count',
        'move_options': 'move_options'
    }

    def __init__(self, flags='dock', back_to_landing=None, charging_retry_count=None, move_options=None):  # noqa: E501
        """GoHomeActionOptionsGohomeOptions - a model defined in Swagger"""  # noqa: E501
        self._flags = None
        self._back_to_landing = None
        self._charging_retry_count = None
        self._move_options = None
        self.discriminator = None
        if flags is not None:
            self.flags = flags
        if back_to_landing is not None:
            self.back_to_landing = back_to_landing
        if charging_retry_count is not None:
            self.charging_retry_count = charging_retry_count
        if move_options is not None:
            self.move_options = move_options

    @property
    def flags(self):
        """Gets the flags of this GoHomeActionOptionsGohomeOptions.  # noqa: E501

        dock表示需要上桩，no_dock表示回到上桩点即可  # noqa: E501

        :return: The flags of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :rtype: str
        """
        return self._flags

    @flags.setter
    def flags(self, flags):
        """Sets the flags of this GoHomeActionOptionsGohomeOptions.

        dock表示需要上桩，no_dock表示回到上桩点即可  # noqa: E501

        :param flags: The flags of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :type: str
        """
        allowed_values = ["dock", "no_dock"]  # noqa: E501
        if flags not in allowed_values:
            raise ValueError(
                "Invalid value for `flags` ({0}), must be one of {1}"  # noqa: E501
                .format(flags, allowed_values)
            )

        self._flags = flags

    @property
    def back_to_landing(self):
        """Gets the back_to_landing of this GoHomeActionOptionsGohomeOptions.  # noqa: E501

        上桩失败后回到上桩点  # noqa: E501

        :return: The back_to_landing of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :rtype: bool
        """
        return self._back_to_landing

    @back_to_landing.setter
    def back_to_landing(self, back_to_landing):
        """Sets the back_to_landing of this GoHomeActionOptionsGohomeOptions.

        上桩失败后回到上桩点  # noqa: E501

        :param back_to_landing: The back_to_landing of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :type: bool
        """

        self._back_to_landing = back_to_landing

    @property
    def charging_retry_count(self):
        """Gets the charging_retry_count of this GoHomeActionOptionsGohomeOptions.  # noqa: E501

        上桩重试次数  # noqa: E501

        :return: The charging_retry_count of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :rtype: int
        """
        return self._charging_retry_count

    @charging_retry_count.setter
    def charging_retry_count(self, charging_retry_count):
        """Sets the charging_retry_count of this GoHomeActionOptionsGohomeOptions.

        上桩重试次数  # noqa: E501

        :param charging_retry_count: The charging_retry_count of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :type: int
        """

        self._charging_retry_count = charging_retry_count

    @property
    def move_options(self):
        """Gets the move_options of this GoHomeActionOptionsGohomeOptions.  # noqa: E501


        :return: The move_options of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :rtype: GoHomeActionOptionsGohomeOptionsMoveOptions
        """
        return self._move_options

    @move_options.setter
    def move_options(self, move_options):
        """Sets the move_options of this GoHomeActionOptionsGohomeOptions.


        :param move_options: The move_options of this GoHomeActionOptionsGohomeOptions.  # noqa: E501
        :type: GoHomeActionOptionsGohomeOptionsMoveOptions
        """

        self._move_options = move_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GoHomeActionOptionsGohomeOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GoHomeActionOptionsGohomeOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
