# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ImuData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'acc': 'Location',
        'availibility_bit_map': 'int',
        'compass': 'Location',
        'euler_angle': 'Location',
        'gyro': 'Location',
        'quaternion': 'Quaternion',
        'raw_acc': 'Location',
        'raw_compass': 'Location',
        'raw_gyro': 'Location',
        'timestamp': 'int'
    }

    attribute_map = {
        'acc': 'acc',
        'availibility_bit_map': 'availibilityBitMap',
        'compass': 'compass',
        'euler_angle': 'euler_angle',
        'gyro': 'gyro',
        'quaternion': 'quaternion',
        'raw_acc': 'raw_acc',
        'raw_compass': 'raw_compass',
        'raw_gyro': 'raw_gyro',
        'timestamp': 'timestamp'
    }

    def __init__(self, acc=None, availibility_bit_map=None, compass=None, euler_angle=None, gyro=None, quaternion=None, raw_acc=None, raw_compass=None, raw_gyro=None, timestamp=None):  # noqa: E501
        """ImuData - a model defined in Swagger"""  # noqa: E501
        self._acc = None
        self._availibility_bit_map = None
        self._compass = None
        self._euler_angle = None
        self._gyro = None
        self._quaternion = None
        self._raw_acc = None
        self._raw_compass = None
        self._raw_gyro = None
        self._timestamp = None
        self.discriminator = None
        if acc is not None:
            self.acc = acc
        if availibility_bit_map is not None:
            self.availibility_bit_map = availibility_bit_map
        if compass is not None:
            self.compass = compass
        if euler_angle is not None:
            self.euler_angle = euler_angle
        if gyro is not None:
            self.gyro = gyro
        if quaternion is not None:
            self.quaternion = quaternion
        if raw_acc is not None:
            self.raw_acc = raw_acc
        if raw_compass is not None:
            self.raw_compass = raw_compass
        if raw_gyro is not None:
            self.raw_gyro = raw_gyro
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def acc(self):
        """Gets the acc of this ImuData.  # noqa: E501


        :return: The acc of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._acc

    @acc.setter
    def acc(self, acc):
        """Sets the acc of this ImuData.


        :param acc: The acc of this ImuData.  # noqa: E501
        :type: Location
        """

        self._acc = acc

    @property
    def availibility_bit_map(self):
        """Gets the availibility_bit_map of this ImuData.  # noqa: E501

        * `1` 以四元数表示的位姿 * `2` 校准后的加速度计 * `4` 校准后的陀螺仪 * `8` 校准后的罗盘 * `16` 加速度计原始值 * `32` 陀螺仪原始值 * `64` 罗盘原始值 * `128` 6自由度的位姿信息 * `256` 9自由度的位姿信息 * `512` 以欧拉角表示的位姿   # noqa: E501

        :return: The availibility_bit_map of this ImuData.  # noqa: E501
        :rtype: int
        """
        return self._availibility_bit_map

    @availibility_bit_map.setter
    def availibility_bit_map(self, availibility_bit_map):
        """Sets the availibility_bit_map of this ImuData.

        * `1` 以四元数表示的位姿 * `2` 校准后的加速度计 * `4` 校准后的陀螺仪 * `8` 校准后的罗盘 * `16` 加速度计原始值 * `32` 陀螺仪原始值 * `64` 罗盘原始值 * `128` 6自由度的位姿信息 * `256` 9自由度的位姿信息 * `512` 以欧拉角表示的位姿   # noqa: E501

        :param availibility_bit_map: The availibility_bit_map of this ImuData.  # noqa: E501
        :type: int
        """

        self._availibility_bit_map = availibility_bit_map

    @property
    def compass(self):
        """Gets the compass of this ImuData.  # noqa: E501


        :return: The compass of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._compass

    @compass.setter
    def compass(self, compass):
        """Sets the compass of this ImuData.


        :param compass: The compass of this ImuData.  # noqa: E501
        :type: Location
        """

        self._compass = compass

    @property
    def euler_angle(self):
        """Gets the euler_angle of this ImuData.  # noqa: E501


        :return: The euler_angle of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._euler_angle

    @euler_angle.setter
    def euler_angle(self, euler_angle):
        """Sets the euler_angle of this ImuData.


        :param euler_angle: The euler_angle of this ImuData.  # noqa: E501
        :type: Location
        """

        self._euler_angle = euler_angle

    @property
    def gyro(self):
        """Gets the gyro of this ImuData.  # noqa: E501


        :return: The gyro of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._gyro

    @gyro.setter
    def gyro(self, gyro):
        """Sets the gyro of this ImuData.


        :param gyro: The gyro of this ImuData.  # noqa: E501
        :type: Location
        """

        self._gyro = gyro

    @property
    def quaternion(self):
        """Gets the quaternion of this ImuData.  # noqa: E501


        :return: The quaternion of this ImuData.  # noqa: E501
        :rtype: Quaternion
        """
        return self._quaternion

    @quaternion.setter
    def quaternion(self, quaternion):
        """Sets the quaternion of this ImuData.


        :param quaternion: The quaternion of this ImuData.  # noqa: E501
        :type: Quaternion
        """

        self._quaternion = quaternion

    @property
    def raw_acc(self):
        """Gets the raw_acc of this ImuData.  # noqa: E501


        :return: The raw_acc of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._raw_acc

    @raw_acc.setter
    def raw_acc(self, raw_acc):
        """Sets the raw_acc of this ImuData.


        :param raw_acc: The raw_acc of this ImuData.  # noqa: E501
        :type: Location
        """

        self._raw_acc = raw_acc

    @property
    def raw_compass(self):
        """Gets the raw_compass of this ImuData.  # noqa: E501


        :return: The raw_compass of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._raw_compass

    @raw_compass.setter
    def raw_compass(self, raw_compass):
        """Sets the raw_compass of this ImuData.


        :param raw_compass: The raw_compass of this ImuData.  # noqa: E501
        :type: Location
        """

        self._raw_compass = raw_compass

    @property
    def raw_gyro(self):
        """Gets the raw_gyro of this ImuData.  # noqa: E501


        :return: The raw_gyro of this ImuData.  # noqa: E501
        :rtype: Location
        """
        return self._raw_gyro

    @raw_gyro.setter
    def raw_gyro(self, raw_gyro):
        """Sets the raw_gyro of this ImuData.


        :param raw_gyro: The raw_gyro of this ImuData.  # noqa: E501
        :type: Location
        """

        self._raw_gyro = raw_gyro

    @property
    def timestamp(self):
        """Gets the timestamp of this ImuData.  # noqa: E501

        底盘启动以来经过的毫秒数  # noqa: E501

        :return: The timestamp of this ImuData.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ImuData.

        底盘启动以来经过的毫秒数  # noqa: E501

        :param timestamp: The timestamp of this ImuData.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ImuData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ImuData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
