# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IndustryTaskRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target': 'str',
        'type': 'str',
        'order_id': 'str',
        'template_key': 'str',
        'start_time': 'str',
        'task_targets': 'list[IndustryTarget]',
        'message': 'object'
    }

    attribute_map = {
        'target': 'target',
        'type': 'type',
        'order_id': 'order_id',
        'template_key': 'template_key',
        'start_time': 'start_time',
        'task_targets': 'task_targets',
        'message': 'message'
    }

    def __init__(self, target=None, type=None, order_id=None, template_key=None, start_time=None, task_targets=None, message=None):  # noqa: E501
        """IndustryTaskRequest - a model defined in Swagger"""  # noqa: E501
        self._target = None
        self._type = None
        self._order_id = None
        self._template_key = None
        self._start_time = None
        self._task_targets = None
        self._message = None
        self.discriminator = None
        if target is not None:
            self.target = target
        if type is not None:
            self.type = type
        if order_id is not None:
            self.order_id = order_id
        if template_key is not None:
            self.template_key = template_key
        if start_time is not None:
            self.start_time = start_time
        if task_targets is not None:
            self.task_targets = task_targets
        if message is not None:
            self.message = message

    @property
    def target(self):
        """Gets the target of this IndustryTaskRequest.  # noqa: E501


        :return: The target of this IndustryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this IndustryTaskRequest.


        :param target: The target of this IndustryTaskRequest.  # noqa: E501
        :type: str
        """

        self._target = target

    @property
    def type(self):
        """Gets the type of this IndustryTaskRequest.  # noqa: E501


        :return: The type of this IndustryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this IndustryTaskRequest.


        :param type: The type of this IndustryTaskRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["CARRY_CALLING", "CARRY_CALLING_BY_TEMPLATE", "INDUSTRY"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def order_id(self):
        """Gets the order_id of this IndustryTaskRequest.  # noqa: E501


        :return: The order_id of this IndustryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this IndustryTaskRequest.


        :param order_id: The order_id of this IndustryTaskRequest.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def template_key(self):
        """Gets the template_key of this IndustryTaskRequest.  # noqa: E501


        :return: The template_key of this IndustryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._template_key

    @template_key.setter
    def template_key(self, template_key):
        """Sets the template_key of this IndustryTaskRequest.


        :param template_key: The template_key of this IndustryTaskRequest.  # noqa: E501
        :type: str
        """

        self._template_key = template_key

    @property
    def start_time(self):
        """Gets the start_time of this IndustryTaskRequest.  # noqa: E501


        :return: The start_time of this IndustryTaskRequest.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this IndustryTaskRequest.


        :param start_time: The start_time of this IndustryTaskRequest.  # noqa: E501
        :type: str
        """

        self._start_time = start_time

    @property
    def task_targets(self):
        """Gets the task_targets of this IndustryTaskRequest.  # noqa: E501


        :return: The task_targets of this IndustryTaskRequest.  # noqa: E501
        :rtype: list[IndustryTarget]
        """
        return self._task_targets

    @task_targets.setter
    def task_targets(self, task_targets):
        """Sets the task_targets of this IndustryTaskRequest.


        :param task_targets: The task_targets of this IndustryTaskRequest.  # noqa: E501
        :type: list[IndustryTarget]
        """

        self._task_targets = task_targets

    @property
    def message(self):
        """Gets the message of this IndustryTaskRequest.  # noqa: E501


        :return: The message of this IndustryTaskRequest.  # noqa: E501
        :rtype: object
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this IndustryTaskRequest.


        :param message: The message of this IndustryTaskRequest.  # noqa: E501
        :type: object
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IndustryTaskRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndustryTaskRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
