# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class IndustryTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'task': 'IndustryTaskRequest',
        'status': 'DeliveryTaskStatus',
        'result': 'IndustryTaskResult'
    }

    attribute_map = {
        'id': 'id',
        'task': 'task',
        'status': 'status',
        'result': 'result'
    }

    def __init__(self, id=None, task=None, status=None, result=None):  # noqa: E501
        """IndustryTask - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._task = None
        self._status = None
        self._result = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if task is not None:
            self.task = task
        if status is not None:
            self.status = status
        if result is not None:
            self.result = result

    @property
    def id(self):
        """Gets the id of this IndustryTask.  # noqa: E501


        :return: The id of this IndustryTask.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this IndustryTask.


        :param id: The id of this IndustryTask.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def task(self):
        """Gets the task of this IndustryTask.  # noqa: E501


        :return: The task of this IndustryTask.  # noqa: E501
        :rtype: IndustryTaskRequest
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this IndustryTask.


        :param task: The task of this IndustryTask.  # noqa: E501
        :type: IndustryTaskRequest
        """

        self._task = task

    @property
    def status(self):
        """Gets the status of this IndustryTask.  # noqa: E501


        :return: The status of this IndustryTask.  # noqa: E501
        :rtype: DeliveryTaskStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this IndustryTask.


        :param status: The status of this IndustryTask.  # noqa: E501
        :type: DeliveryTaskStatus
        """

        self._status = status

    @property
    def result(self):
        """Gets the result of this IndustryTask.  # noqa: E501


        :return: The result of this IndustryTask.  # noqa: E501
        :rtype: IndustryTaskResult
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this IndustryTask.


        :param result: The result of this IndustryTask.  # noqa: E501
        :type: IndustryTaskResult
        """

        self._result = result

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IndustryTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndustryTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
