# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2003(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current': 'float',
        'temp_count': 'int',
        'temp': 'list[int]'
    }

    attribute_map = {
        'current': 'current',
        'temp_count': 'temp_count',
        'temp': 'temp'
    }

    def __init__(self, current=None, temp_count=None, temp=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger"""  # noqa: E501
        self._current = None
        self._temp_count = None
        self._temp = None
        self.discriminator = None
        if current is not None:
            self.current = current
        if temp_count is not None:
            self.temp_count = temp_count
        if temp is not None:
            self.temp = temp

    @property
    def current(self):
        """Gets the current of this InlineResponse2003.  # noqa: E501

        电池包电流，单位mA，正值表示充电，负值表示放电  # noqa: E501

        :return: The current of this InlineResponse2003.  # noqa: E501
        :rtype: float
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this InlineResponse2003.

        电池包电流，单位mA，正值表示充电，负值表示放电  # noqa: E501

        :param current: The current of this InlineResponse2003.  # noqa: E501
        :type: float
        """

        self._current = current

    @property
    def temp_count(self):
        """Gets the temp_count of this InlineResponse2003.  # noqa: E501

        电池包温度传感器数量  # noqa: E501

        :return: The temp_count of this InlineResponse2003.  # noqa: E501
        :rtype: int
        """
        return self._temp_count

    @temp_count.setter
    def temp_count(self, temp_count):
        """Sets the temp_count of this InlineResponse2003.

        电池包温度传感器数量  # noqa: E501

        :param temp_count: The temp_count of this InlineResponse2003.  # noqa: E501
        :type: int
        """

        self._temp_count = temp_count

    @property
    def temp(self):
        """Gets the temp of this InlineResponse2003.  # noqa: E501

        电池包温度传感器温度值，单位0.1摄氏度  # noqa: E501

        :return: The temp of this InlineResponse2003.  # noqa: E501
        :rtype: list[int]
        """
        return self._temp

    @temp.setter
    def temp(self, temp):
        """Sets the temp of this InlineResponse2003.

        电池包温度传感器温度值，单位0.1摄氏度  # noqa: E501

        :param temp: The temp of this InlineResponse2003.  # noqa: E501
        :type: list[int]
        """

        self._temp = temp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2003, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
