# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20024(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'stage': 'str',
        'reason': 'str',
        'cargo_id': 'str',
        'box': 'Box'
    }

    attribute_map = {
        'type': 'type',
        'stage': 'stage',
        'reason': 'reason',
        'cargo_id': 'cargo_id',
        'box': 'box'
    }

    def __init__(self, type=None, stage=None, reason=None, cargo_id=None, box=None):  # noqa: E501
        """InlineResponse20024 - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._stage = None
        self._reason = None
        self._cargo_id = None
        self._box = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if stage is not None:
            self.stage = stage
        if reason is not None:
            self.reason = reason
        if cargo_id is not None:
            self.cargo_id = cargo_id
        if box is not None:
            self.box = box

    @property
    def type(self):
        """Gets the type of this InlineResponse20024.  # noqa: E501

        最近一次舱体操作的类型 OPEN:开门，CLOSE:关门  # noqa: E501

        :return: The type of this InlineResponse20024.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineResponse20024.

        最近一次舱体操作的类型 OPEN:开门，CLOSE:关门  # noqa: E501

        :param type: The type of this InlineResponse20024.  # noqa: E501
        :type: str
        """
        allowed_values = ["OPEN", "CLOSE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def stage(self):
        """Gets the stage of this InlineResponse20024.  # noqa: E501

        操作进度，IN_PROGRESS 执行中， DONE 成功完成， FAILED 失败  # noqa: E501

        :return: The stage of this InlineResponse20024.  # noqa: E501
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage):
        """Sets the stage of this InlineResponse20024.

        操作进度，IN_PROGRESS 执行中， DONE 成功完成， FAILED 失败  # noqa: E501

        :param stage: The stage of this InlineResponse20024.  # noqa: E501
        :type: str
        """
        allowed_values = ["IN_PROGRESS", "DONE", "FAILED"]  # noqa: E501
        if stage not in allowed_values:
            raise ValueError(
                "Invalid value for `stage` ({0}), must be one of {1}"  # noqa: E501
                .format(stage, allowed_values)
            )

        self._stage = stage

    @property
    def reason(self):
        """Gets the reason of this InlineResponse20024.  # noqa: E501


        :return: The reason of this InlineResponse20024.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this InlineResponse20024.


        :param reason: The reason of this InlineResponse20024.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def cargo_id(self):
        """Gets the cargo_id of this InlineResponse20024.  # noqa: E501


        :return: The cargo_id of this InlineResponse20024.  # noqa: E501
        :rtype: str
        """
        return self._cargo_id

    @cargo_id.setter
    def cargo_id(self, cargo_id):
        """Sets the cargo_id of this InlineResponse20024.


        :param cargo_id: The cargo_id of this InlineResponse20024.  # noqa: E501
        :type: str
        """

        self._cargo_id = cargo_id

    @property
    def box(self):
        """Gets the box of this InlineResponse20024.  # noqa: E501


        :return: The box of this InlineResponse20024.  # noqa: E501
        :rtype: Box
        """
        return self._box

    @box.setter
    def box(self, box):
        """Sets the box of this InlineResponse20024.


        :param box: The box of this InlineResponse20024.  # noqa: E501
        :type: Box
        """

        self._box = box

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20024, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20024):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
