# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20014(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_in_mapping_mode': 'bool',
        'map_load_status': 'str',
        'is_managed_by_cloud': 'bool'
    }

    attribute_map = {
        'is_in_mapping_mode': 'is_in_mapping_mode',
        'map_load_status': 'map_load_status',
        'is_managed_by_cloud': 'is_managed_by_cloud'
    }

    def __init__(self, is_in_mapping_mode=None, map_load_status=None, is_managed_by_cloud=None):  # noqa: E501
        """InlineResponse20014 - a model defined in Swagger"""  # noqa: E501
        self._is_in_mapping_mode = None
        self._map_load_status = None
        self._is_managed_by_cloud = None
        self.discriminator = None
        if is_in_mapping_mode is not None:
            self.is_in_mapping_mode = is_in_mapping_mode
        if map_load_status is not None:
            self.map_load_status = map_load_status
        if is_managed_by_cloud is not None:
            self.is_managed_by_cloud = is_managed_by_cloud

    @property
    def is_in_mapping_mode(self):
        """Gets the is_in_mapping_mode of this InlineResponse20014.  # noqa: E501

        是否处于建图模式  # noqa: E501

        :return: The is_in_mapping_mode of this InlineResponse20014.  # noqa: E501
        :rtype: bool
        """
        return self._is_in_mapping_mode

    @is_in_mapping_mode.setter
    def is_in_mapping_mode(self, is_in_mapping_mode):
        """Sets the is_in_mapping_mode of this InlineResponse20014.

        是否处于建图模式  # noqa: E501

        :param is_in_mapping_mode: The is_in_mapping_mode of this InlineResponse20014.  # noqa: E501
        :type: bool
        """

        self._is_in_mapping_mode = is_in_mapping_mode

    @property
    def map_load_status(self):
        """Gets the map_load_status of this InlineResponse20014.  # noqa: E501

        * `NOT_LOADED`本地没有地图文件。 * `LOADING` 正在加载地图。 * `LOADED`成功加载地图。 * `LOADING_SKIPPED` 跳过地图加载步骤，在人为重启单个服务时会进入该状态。 * `NEED_LOAD` 执行任务过程中收到同步云端地图的命令，会等回桩后再自动同步地图。 * `ERROR` 状态异常，地图文件错误或启动楼层信息不匹配   # noqa: E501

        :return: The map_load_status of this InlineResponse20014.  # noqa: E501
        :rtype: str
        """
        return self._map_load_status

    @map_load_status.setter
    def map_load_status(self, map_load_status):
        """Sets the map_load_status of this InlineResponse20014.

        * `NOT_LOADED`本地没有地图文件。 * `LOADING` 正在加载地图。 * `LOADED`成功加载地图。 * `LOADING_SKIPPED` 跳过地图加载步骤，在人为重启单个服务时会进入该状态。 * `NEED_LOAD` 执行任务过程中收到同步云端地图的命令，会等回桩后再自动同步地图。 * `ERROR` 状态异常，地图文件错误或启动楼层信息不匹配   # noqa: E501

        :param map_load_status: The map_load_status of this InlineResponse20014.  # noqa: E501
        :type: str
        """
        allowed_values = ["NOT_LOADED", "LOADING", "LOADED", "LOADING_SKIPPED", "NEED_LOAD", "ERROR"]  # noqa: E501
        if map_load_status not in allowed_values:
            raise ValueError(
                "Invalid value for `map_load_status` ({0}), must be one of {1}"  # noqa: E501
                .format(map_load_status, allowed_values)
            )

        self._map_load_status = map_load_status

    @property
    def is_managed_by_cloud(self):
        """Gets the is_managed_by_cloud of this InlineResponse20014.  # noqa: E501

        是否由云端管理  # noqa: E501

        :return: The is_managed_by_cloud of this InlineResponse20014.  # noqa: E501
        :rtype: bool
        """
        return self._is_managed_by_cloud

    @is_managed_by_cloud.setter
    def is_managed_by_cloud(self, is_managed_by_cloud):
        """Sets the is_managed_by_cloud of this InlineResponse20014.

        是否由云端管理  # noqa: E501

        :param is_managed_by_cloud: The is_managed_by_cloud of this InlineResponse20014.  # noqa: E501
        :type: bool
        """

        self._is_managed_by_cloud = is_managed_by_cloud

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20014, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20014):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
