# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse20017DeliveryAdminPassword(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'enable': 'bool',
        'password': 'str',
        'expires': 'datetime'
    }

    attribute_map = {
        'enable': 'enable',
        'password': 'password',
        'expires': 'expires'
    }

    def __init__(self, enable=None, password=None, expires=None):  # noqa: E501
        """InlineResponse20017DeliveryAdminPassword - a model defined in Swagger"""  # noqa: E501
        self._enable = None
        self._password = None
        self._expires = None
        self.discriminator = None
        self.enable = enable
        if password is not None:
            self.password = password
        if expires is not None:
            self.expires = expires

    @property
    def enable(self):
        """Gets the enable of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501


        :return: The enable of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501
        :rtype: bool
        """
        return self._enable

    @enable.setter
    def enable(self, enable):
        """Sets the enable of this InlineResponse20017DeliveryAdminPassword.


        :param enable: The enable of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501
        :type: bool
        """
        if enable is None:
            raise ValueError("Invalid value for `enable`, must not be `None`")  # noqa: E501

        self._enable = enable

    @property
    def password(self):
        """Gets the password of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501


        :return: The password of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this InlineResponse20017DeliveryAdminPassword.


        :param password: The password of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501
        :type: str
        """

        self._password = password

    @property
    def expires(self):
        """Gets the expires of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501


        :return: The expires of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501
        :rtype: datetime
        """
        return self._expires

    @expires.setter
    def expires(self, expires):
        """Sets the expires of this InlineResponse20017DeliveryAdminPassword.


        :param expires: The expires of this InlineResponse20017DeliveryAdminPassword.  # noqa: E501
        :type: datetime
        """

        self._expires = expires

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20017DeliveryAdminPassword, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20017DeliveryAdminPassword):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
