# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'actual_pos': 'int',
        'alarm': 'int',
        'drv_status': 'int',
        'stage': 'int'
    }

    attribute_map = {
        'actual_pos': 'actual_pos',
        'alarm': 'alarm',
        'drv_status': 'drv_status',
        'stage': 'stage'
    }

    def __init__(self, actual_pos=None, alarm=None, drv_status=None, stage=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._actual_pos = None
        self._alarm = None
        self._drv_status = None
        self._stage = None
        self.discriminator = None
        if actual_pos is not None:
            self.actual_pos = actual_pos
        if alarm is not None:
            self.alarm = alarm
        if drv_status is not None:
            self.drv_status = drv_status
        if stage is not None:
            self.stage = stage

    @property
    def actual_pos(self):
        """Gets the actual_pos of this InlineResponse2001.  # noqa: E501


        :return: The actual_pos of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._actual_pos

    @actual_pos.setter
    def actual_pos(self, actual_pos):
        """Sets the actual_pos of this InlineResponse2001.


        :param actual_pos: The actual_pos of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._actual_pos = actual_pos

    @property
    def alarm(self):
        """Gets the alarm of this InlineResponse2001.  # noqa: E501


        :return: The alarm of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._alarm

    @alarm.setter
    def alarm(self, alarm):
        """Sets the alarm of this InlineResponse2001.


        :param alarm: The alarm of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._alarm = alarm

    @property
    def drv_status(self):
        """Gets the drv_status of this InlineResponse2001.  # noqa: E501


        :return: The drv_status of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._drv_status

    @drv_status.setter
    def drv_status(self, drv_status):
        """Sets the drv_status of this InlineResponse2001.


        :param drv_status: The drv_status of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._drv_status = drv_status

    @property
    def stage(self):
        """Gets the stage of this InlineResponse2001.  # noqa: E501


        :return: The stage of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._stage

    @stage.setter
    def stage(self, stage):
        """Sets the stage of this InlineResponse2001.


        :param stage: The stage of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._stage = stage

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
