# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LaserScanLaserPoints(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'distance': 'float',
        'angle': 'float',
        'valid': 'bool'
    }

    attribute_map = {
        'distance': 'distance',
        'angle': 'angle',
        'valid': 'valid'
    }

    def __init__(self, distance=None, angle=None, valid=None):  # noqa: E501
        """LaserScanLaserPoints - a model defined in Swagger"""  # noqa: E501
        self._distance = None
        self._angle = None
        self._valid = None
        self.discriminator = None
        if distance is not None:
            self.distance = distance
        if angle is not None:
            self.angle = angle
        if valid is not None:
            self.valid = valid

    @property
    def distance(self):
        """Gets the distance of this LaserScanLaserPoints.  # noqa: E501


        :return: The distance of this LaserScanLaserPoints.  # noqa: E501
        :rtype: float
        """
        return self._distance

    @distance.setter
    def distance(self, distance):
        """Sets the distance of this LaserScanLaserPoints.


        :param distance: The distance of this LaserScanLaserPoints.  # noqa: E501
        :type: float
        """

        self._distance = distance

    @property
    def angle(self):
        """Gets the angle of this LaserScanLaserPoints.  # noqa: E501


        :return: The angle of this LaserScanLaserPoints.  # noqa: E501
        :rtype: float
        """
        return self._angle

    @angle.setter
    def angle(self, angle):
        """Sets the angle of this LaserScanLaserPoints.


        :param angle: The angle of this LaserScanLaserPoints.  # noqa: E501
        :type: float
        """

        self._angle = angle

    @property
    def valid(self):
        """Gets the valid of this LaserScanLaserPoints.  # noqa: E501


        :return: The valid of this LaserScanLaserPoints.  # noqa: E501
        :rtype: bool
        """
        return self._valid

    @valid.setter
    def valid(self, valid):
        """Sets the valid of this LaserScanLaserPoints.


        :param valid: The valid of this LaserScanLaserPoints.  # noqa: E501
        :type: bool
        """

        self._valid = valid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LaserScanLaserPoints, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LaserScanLaserPoints):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
