# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LeaveElevatorActionOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elevator_id': 'str',
        'target': 'Pose2D',
        'leave_elevator_options': 'LeaveElevatorOptions'
    }

    attribute_map = {
        'elevator_id': 'elevator_id',
        'target': 'target',
        'leave_elevator_options': 'leave_elevator_options'
    }

    def __init__(self, elevator_id=None, target=None, leave_elevator_options=None):  # noqa: E501
        """LeaveElevatorActionOptions - a model defined in Swagger"""  # noqa: E501
        self._elevator_id = None
        self._target = None
        self._leave_elevator_options = None
        self.discriminator = None
        self.elevator_id = elevator_id
        if target is not None:
            self.target = target
        if leave_elevator_options is not None:
            self.leave_elevator_options = leave_elevator_options

    @property
    def elevator_id(self):
        """Gets the elevator_id of this LeaveElevatorActionOptions.  # noqa: E501


        :return: The elevator_id of this LeaveElevatorActionOptions.  # noqa: E501
        :rtype: str
        """
        return self._elevator_id

    @elevator_id.setter
    def elevator_id(self, elevator_id):
        """Sets the elevator_id of this LeaveElevatorActionOptions.


        :param elevator_id: The elevator_id of this LeaveElevatorActionOptions.  # noqa: E501
        :type: str
        """
        if elevator_id is None:
            raise ValueError("Invalid value for `elevator_id`, must not be `None`")  # noqa: E501

        self._elevator_id = elevator_id

    @property
    def target(self):
        """Gets the target of this LeaveElevatorActionOptions.  # noqa: E501


        :return: The target of this LeaveElevatorActionOptions.  # noqa: E501
        :rtype: Pose2D
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this LeaveElevatorActionOptions.


        :param target: The target of this LeaveElevatorActionOptions.  # noqa: E501
        :type: Pose2D
        """

        self._target = target

    @property
    def leave_elevator_options(self):
        """Gets the leave_elevator_options of this LeaveElevatorActionOptions.  # noqa: E501


        :return: The leave_elevator_options of this LeaveElevatorActionOptions.  # noqa: E501
        :rtype: LeaveElevatorOptions
        """
        return self._leave_elevator_options

    @leave_elevator_options.setter
    def leave_elevator_options(self, leave_elevator_options):
        """Sets the leave_elevator_options of this LeaveElevatorActionOptions.


        :param leave_elevator_options: The leave_elevator_options of this LeaveElevatorActionOptions.  # noqa: E501
        :type: LeaveElevatorOptions
        """

        self._leave_elevator_options = leave_elevator_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LeaveElevatorActionOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LeaveElevatorActionOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
