# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LightControlData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'str',
        'control_part': 'str',
        'mode': 'str',
        'color': 'LightControlDataColor',
        'brightness_end_color': 'LightControlDataBrightnessEndColor',
        'bright_ms': 'int',
        'off_ms': 'int'
    }

    attribute_map = {
        'channel': 'channel',
        'control_part': 'controlPart',
        'mode': 'mode',
        'color': 'color',
        'brightness_end_color': 'brightnessEndColor',
        'bright_ms': 'brightMs',
        'off_ms': 'offMs'
    }

    def __init__(self, channel=None, control_part=None, mode=None, color=None, brightness_end_color=None, bright_ms=None, off_ms=None):  # noqa: E501
        """LightControlData - a model defined in Swagger"""  # noqa: E501
        self._channel = None
        self._control_part = None
        self._mode = None
        self._color = None
        self._brightness_end_color = None
        self._bright_ms = None
        self._off_ms = None
        self.discriminator = None
        if channel is not None:
            self.channel = channel
        if control_part is not None:
            self.control_part = control_part
        if mode is not None:
            self.mode = mode
        if color is not None:
            self.color = color
        if brightness_end_color is not None:
            self.brightness_end_color = brightness_end_color
        if bright_ms is not None:
            self.bright_ms = bright_ms
        if off_ms is not None:
            self.off_ms = off_ms

    @property
    def channel(self):
        """Gets the channel of this LightControlData.  # noqa: E501

        led控制通道:One通道一，Two通道二  # noqa: E501

        :return: The channel of this LightControlData.  # noqa: E501
        :rtype: str
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this LightControlData.

        led控制通道:One通道一，Two通道二  # noqa: E501

        :param channel: The channel of this LightControlData.  # noqa: E501
        :type: str
        """
        allowed_values = ["One", "Two"]  # noqa: E501
        if channel not in allowed_values:
            raise ValueError(
                "Invalid value for `channel` ({0}), must be one of {1}"  # noqa: E501
                .format(channel, allowed_values)
            )

        self._channel = channel

    @property
    def control_part(self):
        """Gets the control_part of this LightControlData.  # noqa: E501

        led控制部分:Left左半部，Right右半部  # noqa: E501

        :return: The control_part of this LightControlData.  # noqa: E501
        :rtype: str
        """
        return self._control_part

    @control_part.setter
    def control_part(self, control_part):
        """Sets the control_part of this LightControlData.

        led控制部分:Left左半部，Right右半部  # noqa: E501

        :param control_part: The control_part of this LightControlData.  # noqa: E501
        :type: str
        """
        allowed_values = ["Left", "Right"]  # noqa: E501
        if control_part not in allowed_values:
            raise ValueError(
                "Invalid value for `control_part` ({0}), must be one of {1}"  # noqa: E501
                .format(control_part, allowed_values)
            )

        self._control_part = control_part

    @property
    def mode(self):
        """Gets the mode of this LightControlData.  # noqa: E501

        led控制模式:AlwaysBright常亮，Breathe呼吸，Blink闪烁，HorseLamp跑马  # noqa: E501

        :return: The mode of this LightControlData.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this LightControlData.

        led控制模式:AlwaysBright常亮，Breathe呼吸，Blink闪烁，HorseLamp跑马  # noqa: E501

        :param mode: The mode of this LightControlData.  # noqa: E501
        :type: str
        """
        allowed_values = ["AlwaysBright", "Breathe", "Blink", "HorseLamp"]  # noqa: E501
        if mode not in allowed_values:
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def color(self):
        """Gets the color of this LightControlData.  # noqa: E501


        :return: The color of this LightControlData.  # noqa: E501
        :rtype: LightControlDataColor
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this LightControlData.


        :param color: The color of this LightControlData.  # noqa: E501
        :type: LightControlDataColor
        """

        self._color = color

    @property
    def brightness_end_color(self):
        """Gets the brightness_end_color of this LightControlData.  # noqa: E501


        :return: The brightness_end_color of this LightControlData.  # noqa: E501
        :rtype: LightControlDataBrightnessEndColor
        """
        return self._brightness_end_color

    @brightness_end_color.setter
    def brightness_end_color(self, brightness_end_color):
        """Sets the brightness_end_color of this LightControlData.


        :param brightness_end_color: The brightness_end_color of this LightControlData.  # noqa: E501
        :type: LightControlDataBrightnessEndColor
        """

        self._brightness_end_color = brightness_end_color

    @property
    def bright_ms(self):
        """Gets the bright_ms of this LightControlData.  # noqa: E501

        常亮模式可填入任意值；呼吸模式填入亮度单次变化时间（单次变化表示color每次增大1的时间）；闪烁模式填入点亮的持续时间；跑马模式表示点亮下一个灯的时间  # noqa: E501

        :return: The bright_ms of this LightControlData.  # noqa: E501
        :rtype: int
        """
        return self._bright_ms

    @bright_ms.setter
    def bright_ms(self, bright_ms):
        """Sets the bright_ms of this LightControlData.

        常亮模式可填入任意值；呼吸模式填入亮度单次变化时间（单次变化表示color每次增大1的时间）；闪烁模式填入点亮的持续时间；跑马模式表示点亮下一个灯的时间  # noqa: E501

        :param bright_ms: The bright_ms of this LightControlData.  # noqa: E501
        :type: int
        """

        self._bright_ms = bright_ms

    @property
    def off_ms(self):
        """Gets the off_ms of this LightControlData.  # noqa: E501

        闪烁模式填入熄灭的持续时间；其他模式可填入任意值  # noqa: E501

        :return: The off_ms of this LightControlData.  # noqa: E501
        :rtype: int
        """
        return self._off_ms

    @off_ms.setter
    def off_ms(self, off_ms):
        """Sets the off_ms of this LightControlData.

        闪烁模式填入熄灭的持续时间；其他模式可填入任意值  # noqa: E501

        :param off_ms: The off_ms of this LightControlData.  # noqa: E501
        :type: int
        """

        self._off_ms = off_ms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LightControlData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LightControlData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
