# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Line(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'start': 'Point',
        'end': 'Point',
        'metadata': 'OneOfLineMetadata'
    }

    attribute_map = {
        'id': 'id',
        'start': 'start',
        'end': 'end',
        'metadata': 'metadata'
    }

    def __init__(self, id=None, start=None, end=None, metadata=None):  # noqa: E501
        """Line - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._start = None
        self._end = None
        self._metadata = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if start is not None:
            self.start = start
        if end is not None:
            self.end = end
        if metadata is not None:
            self.metadata = metadata

    @property
    def id(self):
        """Gets the id of this Line.  # noqa: E501

        如果是添加线段，id会被忽略，如果是编辑线段，则会修改对应id的线段  # noqa: E501

        :return: The id of this Line.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Line.

        如果是添加线段，id会被忽略，如果是编辑线段，则会修改对应id的线段  # noqa: E501

        :param id: The id of this Line.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def start(self):
        """Gets the start of this Line.  # noqa: E501


        :return: The start of this Line.  # noqa: E501
        :rtype: Point
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this Line.


        :param start: The start of this Line.  # noqa: E501
        :type: Point
        """

        self._start = start

    @property
    def end(self):
        """Gets the end of this Line.  # noqa: E501


        :return: The end of this Line.  # noqa: E501
        :rtype: Point
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Line.


        :param end: The end of this Line.  # noqa: E501
        :type: Point
        """

        self._end = end

    @property
    def metadata(self):
        """Gets the metadata of this Line.  # noqa: E501

        如果是直线轨道，metadata为EmptyMetadata，如果是贝塞尔曲线轨道，metadata为BezierCurveMetadata  # noqa: E501

        :return: The metadata of this Line.  # noqa: E501
        :rtype: OneOfLineMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """Sets the metadata of this Line.

        如果是直线轨道，metadata为EmptyMetadata，如果是贝塞尔曲线轨道，metadata为BezierCurveMetadata  # noqa: E501

        :param metadata: The metadata of this Line.  # noqa: E501
        :type: OneOfLineMetadata
        """

        self._metadata = metadata

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Line, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Line):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
