# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MoveToTagActionOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'target': 'Pose3D',
        'tag_type': 'int',
        'target_relative_pose': 'MoveToTagActionOptionsTargetRelativePose',
        'backward_docking': 'bool',
        'turn_radian': 'float',
        'tag_ids': 'list[int]',
        'reflect_tag_num': 'int',
        'dock_retry_count': 'int',
        'dock_allowance': 'float'
    }

    attribute_map = {
        'target': 'target',
        'tag_type': 'tag_type',
        'target_relative_pose': 'target_relative_pose',
        'backward_docking': 'backward_docking',
        'turn_radian': 'turn_radian',
        'tag_ids': 'tag_ids',
        'reflect_tag_num': 'reflect_tag_num',
        'dock_retry_count': 'dock_retry_count',
        'dock_allowance': 'dock_allowance'
    }

    def __init__(self, target=None, tag_type=Tag_typeEnum._0, target_relative_pose=None, backward_docking=False, turn_radian=None, tag_ids=None, reflect_tag_num=None, dock_retry_count=None, dock_allowance=None):  # noqa: E501
        """MoveToTagActionOptions - a model defined in Swagger"""  # noqa: E501
        self._target = None
        self._tag_type = None
        self._target_relative_pose = None
        self._backward_docking = None
        self._turn_radian = None
        self._tag_ids = None
        self._reflect_tag_num = None
        self._dock_retry_count = None
        self._dock_allowance = None
        self.discriminator = None
        self.target = target
        self.tag_type = tag_type
        if target_relative_pose is not None:
            self.target_relative_pose = target_relative_pose
        if backward_docking is not None:
            self.backward_docking = backward_docking
        if turn_radian is not None:
            self.turn_radian = turn_radian
        if tag_ids is not None:
            self.tag_ids = tag_ids
        if reflect_tag_num is not None:
            self.reflect_tag_num = reflect_tag_num
        if dock_retry_count is not None:
            self.dock_retry_count = dock_retry_count
        if dock_allowance is not None:
            self.dock_allowance = dock_allowance

    @property
    def target(self):
        """Gets the target of this MoveToTagActionOptions.  # noqa: E501


        :return: The target of this MoveToTagActionOptions.  # noqa: E501
        :rtype: Pose3D
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this MoveToTagActionOptions.


        :param target: The target of this MoveToTagActionOptions.  # noqa: E501
        :type: Pose3D
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501

        self._target = target

    @property
    def tag_type(self):
        """Gets the tag_type of this MoveToTagActionOptions.  # noqa: E501

        0：二维码视觉标签， 1：激光标签, 2：激光反光板, 3：货架(需要6.0或更高版本)  # noqa: E501

        :return: The tag_type of this MoveToTagActionOptions.  # noqa: E501
        :rtype: int
        """
        return self._tag_type

    @tag_type.setter
    def tag_type(self, tag_type):
        """Sets the tag_type of this MoveToTagActionOptions.

        0：二维码视觉标签， 1：激光标签, 2：激光反光板, 3：货架(需要6.0或更高版本)  # noqa: E501

        :param tag_type: The tag_type of this MoveToTagActionOptions.  # noqa: E501
        :type: int
        """
        if tag_type is None:
            raise ValueError("Invalid value for `tag_type`, must not be `None`")  # noqa: E501
        allowed_values = [0, 1, 2, 3]  # noqa: E501
        if tag_type not in allowed_values:
            raise ValueError(
                "Invalid value for `tag_type` ({0}), must be one of {1}"  # noqa: E501
                .format(tag_type, allowed_values)
            )

        self._tag_type = tag_type

    @property
    def target_relative_pose(self):
        """Gets the target_relative_pose of this MoveToTagActionOptions.  # noqa: E501


        :return: The target_relative_pose of this MoveToTagActionOptions.  # noqa: E501
        :rtype: MoveToTagActionOptionsTargetRelativePose
        """
        return self._target_relative_pose

    @target_relative_pose.setter
    def target_relative_pose(self, target_relative_pose):
        """Sets the target_relative_pose of this MoveToTagActionOptions.


        :param target_relative_pose: The target_relative_pose of this MoveToTagActionOptions.  # noqa: E501
        :type: MoveToTagActionOptionsTargetRelativePose
        """

        self._target_relative_pose = target_relative_pose

    @property
    def backward_docking(self):
        """Gets the backward_docking of this MoveToTagActionOptions.  # noqa: E501

        是否向后对接  # noqa: E501

        :return: The backward_docking of this MoveToTagActionOptions.  # noqa: E501
        :rtype: bool
        """
        return self._backward_docking

    @backward_docking.setter
    def backward_docking(self, backward_docking):
        """Sets the backward_docking of this MoveToTagActionOptions.

        是否向后对接  # noqa: E501

        :param backward_docking: The backward_docking of this MoveToTagActionOptions.  # noqa: E501
        :type: bool
        """

        self._backward_docking = backward_docking

    @property
    def turn_radian(self):
        """Gets the turn_radian of this MoveToTagActionOptions.  # noqa: E501

        对接成功后的转向弧度，默认机器是面向或背对Tag，如果需要机器在对接成功后转指定角度，请设置该字段。  # noqa: E501

        :return: The turn_radian of this MoveToTagActionOptions.  # noqa: E501
        :rtype: float
        """
        return self._turn_radian

    @turn_radian.setter
    def turn_radian(self, turn_radian):
        """Sets the turn_radian of this MoveToTagActionOptions.

        对接成功后的转向弧度，默认机器是面向或背对Tag，如果需要机器在对接成功后转指定角度，请设置该字段。  # noqa: E501

        :param turn_radian: The turn_radian of this MoveToTagActionOptions.  # noqa: E501
        :type: float
        """

        self._turn_radian = turn_radian

    @property
    def tag_ids(self):
        """Gets the tag_ids of this MoveToTagActionOptions.  # noqa: E501

        tag_type为0时有效，二维码ID  # noqa: E501

        :return: The tag_ids of this MoveToTagActionOptions.  # noqa: E501
        :rtype: list[int]
        """
        return self._tag_ids

    @tag_ids.setter
    def tag_ids(self, tag_ids):
        """Sets the tag_ids of this MoveToTagActionOptions.

        tag_type为0时有效，二维码ID  # noqa: E501

        :param tag_ids: The tag_ids of this MoveToTagActionOptions.  # noqa: E501
        :type: list[int]
        """

        self._tag_ids = tag_ids

    @property
    def reflect_tag_num(self):
        """Gets the reflect_tag_num of this MoveToTagActionOptions.  # noqa: E501

        tag_type为2时有效，对接的反光板个数，默认为1.  # noqa: E501

        :return: The reflect_tag_num of this MoveToTagActionOptions.  # noqa: E501
        :rtype: int
        """
        return self._reflect_tag_num

    @reflect_tag_num.setter
    def reflect_tag_num(self, reflect_tag_num):
        """Sets the reflect_tag_num of this MoveToTagActionOptions.

        tag_type为2时有效，对接的反光板个数，默认为1.  # noqa: E501

        :param reflect_tag_num: The reflect_tag_num of this MoveToTagActionOptions.  # noqa: E501
        :type: int
        """

        self._reflect_tag_num = reflect_tag_num

    @property
    def dock_retry_count(self):
        """Gets the dock_retry_count of this MoveToTagActionOptions.  # noqa: E501

        对接失败后的重试次数，默认不重试.  # noqa: E501

        :return: The dock_retry_count of this MoveToTagActionOptions.  # noqa: E501
        :rtype: int
        """
        return self._dock_retry_count

    @dock_retry_count.setter
    def dock_retry_count(self, dock_retry_count):
        """Sets the dock_retry_count of this MoveToTagActionOptions.

        对接失败后的重试次数，默认不重试.  # noqa: E501

        :param dock_retry_count: The dock_retry_count of this MoveToTagActionOptions.  # noqa: E501
        :type: int
        """

        self._dock_retry_count = dock_retry_count

    @property
    def dock_allowance(self):
        """Gets the dock_allowance of this MoveToTagActionOptions.  # noqa: E501

        tag_type为3时有效，对接货架时默认机器中心对准货架中心。dock_allowance表示机器人留在货架外的机身长度。  # noqa: E501

        :return: The dock_allowance of this MoveToTagActionOptions.  # noqa: E501
        :rtype: float
        """
        return self._dock_allowance

    @dock_allowance.setter
    def dock_allowance(self, dock_allowance):
        """Sets the dock_allowance of this MoveToTagActionOptions.

        tag_type为3时有效，对接货架时默认机器中心对准货架中心。dock_allowance表示机器人留在货架外的机身长度。  # noqa: E501

        :param dock_allowance: The dock_allowance of this MoveToTagActionOptions.  # noqa: E501
        :type: float
        """

        self._dock_allowance = dock_allowance

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MoveToTagActionOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MoveToTagActionOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
