# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MultiFloorDockInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'dock_name': 'str',
        'floor': 'str',
        'building': 'str',
        'pose': 'Pose2D'
    }

    attribute_map = {
        'id': 'id',
        'dock_name': 'dock_name',
        'floor': 'floor',
        'building': 'building',
        'pose': 'pose'
    }

    def __init__(self, id=None, dock_name=None, floor=None, building=None, pose=None):  # noqa: E501
        """MultiFloorDockInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._dock_name = None
        self._floor = None
        self._building = None
        self._pose = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if dock_name is not None:
            self.dock_name = dock_name
        if floor is not None:
            self.floor = floor
        if building is not None:
            self.building = building
        if pose is not None:
            self.pose = pose

    @property
    def id(self):
        """Gets the id of this MultiFloorDockInfo.  # noqa: E501


        :return: The id of this MultiFloorDockInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MultiFloorDockInfo.


        :param id: The id of this MultiFloorDockInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def dock_name(self):
        """Gets the dock_name of this MultiFloorDockInfo.  # noqa: E501


        :return: The dock_name of this MultiFloorDockInfo.  # noqa: E501
        :rtype: str
        """
        return self._dock_name

    @dock_name.setter
    def dock_name(self, dock_name):
        """Sets the dock_name of this MultiFloorDockInfo.


        :param dock_name: The dock_name of this MultiFloorDockInfo.  # noqa: E501
        :type: str
        """

        self._dock_name = dock_name

    @property
    def floor(self):
        """Gets the floor of this MultiFloorDockInfo.  # noqa: E501


        :return: The floor of this MultiFloorDockInfo.  # noqa: E501
        :rtype: str
        """
        return self._floor

    @floor.setter
    def floor(self, floor):
        """Sets the floor of this MultiFloorDockInfo.


        :param floor: The floor of this MultiFloorDockInfo.  # noqa: E501
        :type: str
        """

        self._floor = floor

    @property
    def building(self):
        """Gets the building of this MultiFloorDockInfo.  # noqa: E501


        :return: The building of this MultiFloorDockInfo.  # noqa: E501
        :rtype: str
        """
        return self._building

    @building.setter
    def building(self, building):
        """Sets the building of this MultiFloorDockInfo.


        :param building: The building of this MultiFloorDockInfo.  # noqa: E501
        :type: str
        """

        self._building = building

    @property
    def pose(self):
        """Gets the pose of this MultiFloorDockInfo.  # noqa: E501


        :return: The pose of this MultiFloorDockInfo.  # noqa: E501
        :rtype: Pose2D
        """
        return self._pose

    @pose.setter
    def pose(self, pose):
        """Sets the pose of this MultiFloorDockInfo.


        :param pose: The pose of this MultiFloorDockInfo.  # noqa: E501
        :type: Pose2D
        """

        self._pose = pose

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MultiFloorDockInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MultiFloorDockInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
