# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NearbyPoiInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'OneOfNearbyPoiInfoName',
        'relative_pose': 'Point'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'relative_pose': 'relative_pose'
    }

    def __init__(self, id=None, name=None, relative_pose=None):  # noqa: E501
        """NearbyPoiInfo - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._relative_pose = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        if relative_pose is not None:
            self.relative_pose = relative_pose

    @property
    def id(self):
        """Gets the id of this NearbyPoiInfo.  # noqa: E501


        :return: The id of this NearbyPoiInfo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NearbyPoiInfo.


        :param id: The id of this NearbyPoiInfo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this NearbyPoiInfo.  # noqa: E501


        :return: The name of this NearbyPoiInfo.  # noqa: E501
        :rtype: OneOfNearbyPoiInfoName
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NearbyPoiInfo.


        :param name: The name of this NearbyPoiInfo.  # noqa: E501
        :type: OneOfNearbyPoiInfoName
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def relative_pose(self):
        """Gets the relative_pose of this NearbyPoiInfo.  # noqa: E501


        :return: The relative_pose of this NearbyPoiInfo.  # noqa: E501
        :rtype: Point
        """
        return self._relative_pose

    @relative_pose.setter
    def relative_pose(self, relative_pose):
        """Sets the relative_pose of this NearbyPoiInfo.


        :param relative_pose: The relative_pose of this NearbyPoiInfo.  # noqa: E501
        :type: Point
        """

        self._relative_pose = relative_pose

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NearbyPoiInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NearbyPoiInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
