# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NetworkStatusBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'networkmode': 'int',
        'options': 'OneOfnetworkStatusBodyOptions'
    }

    attribute_map = {
        'networkmode': 'networkmode',
        'options': 'options'
    }

    def __init__(self, networkmode=None, options=None):  # noqa: E501
        """NetworkStatusBody - a model defined in Swagger"""  # noqa: E501
        self._networkmode = None
        self._options = None
        self.discriminator = None
        if networkmode is not None:
            self.networkmode = networkmode
        if options is not None:
            self.options = options

    @property
    def networkmode(self):
        """Gets the networkmode of this NetworkStatusBody.  # noqa: E501

        网络模式:   * `0` - 设为AP模式    * `1` - 设为Station模式   * `2` - 禁用WIFI   * `3` - 禁用DHCP   * `4` - 启用DHCP   # noqa: E501

        :return: The networkmode of this NetworkStatusBody.  # noqa: E501
        :rtype: int
        """
        return self._networkmode

    @networkmode.setter
    def networkmode(self, networkmode):
        """Sets the networkmode of this NetworkStatusBody.

        网络模式:   * `0` - 设为AP模式    * `1` - 设为Station模式   * `2` - 禁用WIFI   * `3` - 禁用DHCP   * `4` - 启用DHCP   # noqa: E501

        :param networkmode: The networkmode of this NetworkStatusBody.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1, 2, 3, 4]  # noqa: E501
        if networkmode not in allowed_values:
            raise ValueError(
                "Invalid value for `networkmode` ({0}), must be one of {1}"  # noqa: E501
                .format(networkmode, allowed_values)
            )

        self._networkmode = networkmode

    @property
    def options(self):
        """Gets the options of this NetworkStatusBody.  # noqa: E501


        :return: The options of this NetworkStatusBody.  # noqa: E501
        :rtype: OneOfnetworkStatusBodyOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this NetworkStatusBody.


        :param options: The options of this NetworkStatusBody.  # noqa: E501
        :type: OneOfnetworkStatusBodyOptions
        """

        self._options = options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkStatusBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkStatusBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
