# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OnDeliveringStage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'stage': 'str',
        'milestone': 'DeliveryTaskEventStage',
        'current_floor': 'str',
        'target_floor': 'str',
        'info': 'OnDeliveringStageInfo'
    }

    attribute_map = {
        'stage': 'stage',
        'milestone': 'milestone',
        'current_floor': 'current_floor',
        'target_floor': 'target_floor',
        'info': 'info'
    }

    def __init__(self, stage=None, milestone=None, current_floor=None, target_floor=None, info=None):  # noqa: E501
        """OnDeliveringStage - a model defined in Swagger"""  # noqa: E501
        self._stage = None
        self._milestone = None
        self._current_floor = None
        self._target_floor = None
        self._info = None
        self.discriminator = None
        if stage is not None:
            self.stage = stage
        if milestone is not None:
            self.milestone = milestone
        if current_floor is not None:
            self.current_floor = current_floor
        if target_floor is not None:
            self.target_floor = target_floor
        if info is not None:
            self.info = info

    @property
    def stage(self):
        """Gets the stage of this OnDeliveringStage.  # noqa: E501


        :return: The stage of this OnDeliveringStage.  # noqa: E501
        :rtype: str
        """
        return self._stage

    @stage.setter
    def stage(self, stage):
        """Sets the stage of this OnDeliveringStage.


        :param stage: The stage of this OnDeliveringStage.  # noqa: E501
        :type: str
        """
        allowed_values = ["ON_DELIVERING"]  # noqa: E501
        if stage not in allowed_values:
            raise ValueError(
                "Invalid value for `stage` ({0}), must be one of {1}"  # noqa: E501
                .format(stage, allowed_values)
            )

        self._stage = stage

    @property
    def milestone(self):
        """Gets the milestone of this OnDeliveringStage.  # noqa: E501


        :return: The milestone of this OnDeliveringStage.  # noqa: E501
        :rtype: DeliveryTaskEventStage
        """
        return self._milestone

    @milestone.setter
    def milestone(self, milestone):
        """Sets the milestone of this OnDeliveringStage.


        :param milestone: The milestone of this OnDeliveringStage.  # noqa: E501
        :type: DeliveryTaskEventStage
        """

        self._milestone = milestone

    @property
    def current_floor(self):
        """Gets the current_floor of this OnDeliveringStage.  # noqa: E501


        :return: The current_floor of this OnDeliveringStage.  # noqa: E501
        :rtype: str
        """
        return self._current_floor

    @current_floor.setter
    def current_floor(self, current_floor):
        """Sets the current_floor of this OnDeliveringStage.


        :param current_floor: The current_floor of this OnDeliveringStage.  # noqa: E501
        :type: str
        """

        self._current_floor = current_floor

    @property
    def target_floor(self):
        """Gets the target_floor of this OnDeliveringStage.  # noqa: E501


        :return: The target_floor of this OnDeliveringStage.  # noqa: E501
        :rtype: str
        """
        return self._target_floor

    @target_floor.setter
    def target_floor(self, target_floor):
        """Sets the target_floor of this OnDeliveringStage.


        :param target_floor: The target_floor of this OnDeliveringStage.  # noqa: E501
        :type: str
        """

        self._target_floor = target_floor

    @property
    def info(self):
        """Gets the info of this OnDeliveringStage.  # noqa: E501


        :return: The info of this OnDeliveringStage.  # noqa: E501
        :rtype: OnDeliveringStageInfo
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this OnDeliveringStage.


        :param info: The info of this OnDeliveringStage.  # noqa: E501
        :type: OnDeliveringStageInfo
        """

        self._info = info

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OnDeliveringStage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OnDeliveringStage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
