# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Pose2D(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'x': 'float',
        'y': 'float',
        'yaw': 'float'
    }

    attribute_map = {
        'x': 'x',
        'y': 'y',
        'yaw': 'yaw'
    }

    def __init__(self, x=None, y=None, yaw=None):  # noqa: E501
        """Pose2D - a model defined in Swagger"""  # noqa: E501
        self._x = None
        self._y = None
        self._yaw = None
        self.discriminator = None
        if x is not None:
            self.x = x
        if y is not None:
            self.y = y
        if yaw is not None:
            self.yaw = yaw

    @property
    def x(self):
        """Gets the x of this Pose2D.  # noqa: E501


        :return: The x of this Pose2D.  # noqa: E501
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this Pose2D.


        :param x: The x of this Pose2D.  # noqa: E501
        :type: float
        """

        self._x = x

    @property
    def y(self):
        """Gets the y of this Pose2D.  # noqa: E501


        :return: The y of this Pose2D.  # noqa: E501
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this Pose2D.


        :param y: The y of this Pose2D.  # noqa: E501
        :type: float
        """

        self._y = y

    @property
    def yaw(self):
        """Gets the yaw of this Pose2D.  # noqa: E501


        :return: The yaw of this Pose2D.  # noqa: E501
        :rtype: float
        """
        return self._yaw

    @yaw.setter
    def yaw(self, yaw):
        """Sets the yaw of this Pose2D.


        :param yaw: The yaw of this Pose2D.  # noqa: E501
        :type: float
        """

        self._yaw = yaw

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Pose2D, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Pose2D):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
