# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PostTaskRequestEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location': 'PostTaskRequestEntryLocation',
        'type': 'str',
        'cargos': 'list[CargoEntry]'
    }

    attribute_map = {
        'location': 'location',
        'type': 'type',
        'cargos': 'cargos'
    }

    def __init__(self, location=None, type=None, cargos=None):  # noqa: E501
        """PostTaskRequestEntry - a model defined in Swagger"""  # noqa: E501
        self._location = None
        self._type = None
        self._cargos = None
        self.discriminator = None
        if location is not None:
            self.location = location
        if type is not None:
            self.type = type
        if cargos is not None:
            self.cargos = cargos

    @property
    def location(self):
        """Gets the location of this PostTaskRequestEntry.  # noqa: E501


        :return: The location of this PostTaskRequestEntry.  # noqa: E501
        :rtype: PostTaskRequestEntryLocation
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this PostTaskRequestEntry.


        :param location: The location of this PostTaskRequestEntry.  # noqa: E501
        :type: PostTaskRequestEntryLocation
        """

        self._location = location

    @property
    def type(self):
        """Gets the type of this PostTaskRequestEntry.  # noqa: E501

        * `TAKEOUT` 外卖配送任务（仅限有货仓的机型）  * `GUIDE` 引领任务，将人带到指定目的地 * `FOOD_DELIVERY` 送餐任务 * `RETURN` 快速返航，回到取餐点 * `RECYCLE` 回收餐盘 * `TAKEOUT_DISTRIBUTE` 外卖分发，打开所有舱门由用户自主取物   # noqa: E501

        :return: The type of this PostTaskRequestEntry.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PostTaskRequestEntry.

        * `TAKEOUT` 外卖配送任务（仅限有货仓的机型）  * `GUIDE` 引领任务，将人带到指定目的地 * `FOOD_DELIVERY` 送餐任务 * `RETURN` 快速返航，回到取餐点 * `RECYCLE` 回收餐盘 * `TAKEOUT_DISTRIBUTE` 外卖分发，打开所有舱门由用户自主取物   # noqa: E501

        :param type: The type of this PostTaskRequestEntry.  # noqa: E501
        :type: str
        """
        allowed_values = ["TAKEOUT", "GUIDE", "FOOD_DELIVERY", "RETURN", "RECYCLE", "TAKEOUT_DISTRIBUTE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def cargos(self):
        """Gets the cargos of this PostTaskRequestEntry.  # noqa: E501


        :return: The cargos of this PostTaskRequestEntry.  # noqa: E501
        :rtype: list[CargoEntry]
        """
        return self._cargos

    @cargos.setter
    def cargos(self, cargos):
        """Sets the cargos of this PostTaskRequestEntry.


        :param cargos: The cargos of this PostTaskRequestEntry.  # noqa: E501
        :type: list[CargoEntry]
        """

        self._cargos = cargos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostTaskRequestEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostTaskRequestEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
