# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PostTaskRequestEntryLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'poi_name': 'str',
        'task_points': 'list[str]'
    }

    attribute_map = {
        'poi_name': 'poi_name',
        'task_points': 'task_points'
    }

    def __init__(self, poi_name=None, task_points=None):  # noqa: E501
        """PostTaskRequestEntryLocation - a model defined in Swagger"""  # noqa: E501
        self._poi_name = None
        self._task_points = None
        self.discriminator = None
        if poi_name is not None:
            self.poi_name = poi_name
        if task_points is not None:
            self.task_points = task_points

    @property
    def poi_name(self):
        """Gets the poi_name of this PostTaskRequestEntryLocation.  # noqa: E501

        任务目的地  # noqa: E501

        :return: The poi_name of this PostTaskRequestEntryLocation.  # noqa: E501
        :rtype: str
        """
        return self._poi_name

    @poi_name.setter
    def poi_name(self, poi_name):
        """Sets the poi_name of this PostTaskRequestEntryLocation.

        任务目的地  # noqa: E501

        :param poi_name: The poi_name of this PostTaskRequestEntryLocation.  # noqa: E501
        :type: str
        """

        self._poi_name = poi_name

    @property
    def task_points(self):
        """Gets the task_points of this PostTaskRequestEntryLocation.  # noqa: E501

        任务点，表示执行任务过程中需要停靠的点, 不需要的话为空即可。  # noqa: E501

        :return: The task_points of this PostTaskRequestEntryLocation.  # noqa: E501
        :rtype: list[str]
        """
        return self._task_points

    @task_points.setter
    def task_points(self, task_points):
        """Sets the task_points of this PostTaskRequestEntryLocation.

        任务点，表示执行任务过程中需要停靠的点, 不需要的话为空即可。  # noqa: E501

        :param task_points: The task_points of this PostTaskRequestEntryLocation.  # noqa: E501
        :type: list[str]
        """

        self._task_points = task_points

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostTaskRequestEntryLocation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostTaskRequestEntryLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
