# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PowerShutdownBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'shutdown_time_interval': 'int',
        'restart_time_interval': 'int'
    }

    attribute_map = {
        'shutdown_time_interval': 'shutdown_time_interval',
        'restart_time_interval': 'restart_time_interval'
    }

    def __init__(self, shutdown_time_interval=None, restart_time_interval=None):  # noqa: E501
        """PowerShutdownBody - a model defined in Swagger"""  # noqa: E501
        self._shutdown_time_interval = None
        self._restart_time_interval = None
        self.discriminator = None
        if shutdown_time_interval is not None:
            self.shutdown_time_interval = shutdown_time_interval
        if restart_time_interval is not None:
            self.restart_time_interval = restart_time_interval

    @property
    def shutdown_time_interval(self):
        """Gets the shutdown_time_interval of this PowerShutdownBody.  # noqa: E501

        关机时间  # noqa: E501

        :return: The shutdown_time_interval of this PowerShutdownBody.  # noqa: E501
        :rtype: int
        """
        return self._shutdown_time_interval

    @shutdown_time_interval.setter
    def shutdown_time_interval(self, shutdown_time_interval):
        """Sets the shutdown_time_interval of this PowerShutdownBody.

        关机时间  # noqa: E501

        :param shutdown_time_interval: The shutdown_time_interval of this PowerShutdownBody.  # noqa: E501
        :type: int
        """

        self._shutdown_time_interval = shutdown_time_interval

    @property
    def restart_time_interval(self):
        """Gets the restart_time_interval of this PowerShutdownBody.  # noqa: E501

        重启时间  # noqa: E501

        :return: The restart_time_interval of this PowerShutdownBody.  # noqa: E501
        :rtype: int
        """
        return self._restart_time_interval

    @restart_time_interval.setter
    def restart_time_interval(self, restart_time_interval):
        """Sets the restart_time_interval of this PowerShutdownBody.

        重启时间  # noqa: E501

        :param restart_time_interval: The restart_time_interval of this PowerShutdownBody.  # noqa: E501
        :type: int
        """

        self._restart_time_interval = restart_time_interval

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PowerShutdownBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PowerShutdownBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
