# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecoverLocalizationActionOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'area': 'Rectangle',
        'relocalization_options': 'RecoverLocalizationActionOptionsRelocalizationOptions'
    }

    attribute_map = {
        'area': 'area',
        'relocalization_options': 'relocalization_options'
    }

    def __init__(self, area=None, relocalization_options=None):  # noqa: E501
        """RecoverLocalizationActionOptions - a model defined in Swagger"""  # noqa: E501
        self._area = None
        self._relocalization_options = None
        self.discriminator = None
        if area is not None:
            self.area = area
        if relocalization_options is not None:
            self.relocalization_options = relocalization_options

    @property
    def area(self):
        """Gets the area of this RecoverLocalizationActionOptions.  # noqa: E501


        :return: The area of this RecoverLocalizationActionOptions.  # noqa: E501
        :rtype: Rectangle
        """
        return self._area

    @area.setter
    def area(self, area):
        """Sets the area of this RecoverLocalizationActionOptions.


        :param area: The area of this RecoverLocalizationActionOptions.  # noqa: E501
        :type: Rectangle
        """

        self._area = area

    @property
    def relocalization_options(self):
        """Gets the relocalization_options of this RecoverLocalizationActionOptions.  # noqa: E501


        :return: The relocalization_options of this RecoverLocalizationActionOptions.  # noqa: E501
        :rtype: RecoverLocalizationActionOptionsRelocalizationOptions
        """
        return self._relocalization_options

    @relocalization_options.setter
    def relocalization_options(self, relocalization_options):
        """Sets the relocalization_options of this RecoverLocalizationActionOptions.


        :param relocalization_options: The relocalization_options of this RecoverLocalizationActionOptions.  # noqa: E501
        :type: RecoverLocalizationActionOptionsRelocalizationOptions
        """

        self._relocalization_options = relocalization_options

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecoverLocalizationActionOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecoverLocalizationActionOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
