# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RecoverLocalizationActionOptionsRelocalizationOptions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max_recover_time': 'int',
        'recover_movement_type': 'str'
    }

    attribute_map = {
        'max_recover_time': 'max_recover_time',
        'recover_movement_type': 'recover_movement_type'
    }

    def __init__(self, max_recover_time=None, recover_movement_type=None):  # noqa: E501
        """RecoverLocalizationActionOptionsRelocalizationOptions - a model defined in Swagger"""  # noqa: E501
        self._max_recover_time = None
        self._recover_movement_type = None
        self.discriminator = None
        if max_recover_time is not None:
            self.max_recover_time = max_recover_time
        if recover_movement_type is not None:
            self.recover_movement_type = recover_movement_type

    @property
    def max_recover_time(self):
        """Gets the max_recover_time of this RecoverLocalizationActionOptionsRelocalizationOptions.  # noqa: E501

        重定位超时时间，单位毫秒  # noqa: E501

        :return: The max_recover_time of this RecoverLocalizationActionOptionsRelocalizationOptions.  # noqa: E501
        :rtype: int
        """
        return self._max_recover_time

    @max_recover_time.setter
    def max_recover_time(self, max_recover_time):
        """Sets the max_recover_time of this RecoverLocalizationActionOptionsRelocalizationOptions.

        重定位超时时间，单位毫秒  # noqa: E501

        :param max_recover_time: The max_recover_time of this RecoverLocalizationActionOptionsRelocalizationOptions.  # noqa: E501
        :type: int
        """

        self._max_recover_time = max_recover_time

    @property
    def recover_movement_type(self):
        """Gets the recover_movement_type of this RecoverLocalizationActionOptionsRelocalizationOptions.  # noqa: E501

        * `RotateOnly` 旋转重定位  * `NoMove` 静止重定位    # noqa: E501

        :return: The recover_movement_type of this RecoverLocalizationActionOptionsRelocalizationOptions.  # noqa: E501
        :rtype: str
        """
        return self._recover_movement_type

    @recover_movement_type.setter
    def recover_movement_type(self, recover_movement_type):
        """Sets the recover_movement_type of this RecoverLocalizationActionOptionsRelocalizationOptions.

        * `RotateOnly` 旋转重定位  * `NoMove` 静止重定位    # noqa: E501

        :param recover_movement_type: The recover_movement_type of this RecoverLocalizationActionOptionsRelocalizationOptions.  # noqa: E501
        :type: str
        """
        allowed_values = ["RotateOnly", "NoMove"]  # noqa: E501
        if recover_movement_type not in allowed_values:
            raise ValueError(
                "Invalid value for `recover_movement_type` ({0}), must be one of {1}"  # noqa: E501
                .format(recover_movement_type, allowed_values)
            )

        self._recover_movement_type = recover_movement_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RecoverLocalizationActionOptionsRelocalizationOptions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecoverLocalizationActionOptionsRelocalizationOptions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
