# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RouteStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'priority': 'str'
    }

    attribute_map = {
        'priority': 'priority'
    }

    def __init__(self, priority=None):  # noqa: E501
        """RouteStatus - a model defined in Swagger"""  # noqa: E501
        self._priority = None
        self.discriminator = None
        if priority is not None:
            self.priority = priority

    @property
    def priority(self):
        """Gets the priority of this RouteStatus.  # noqa: E501

        路由优先级选择:   * `wifi` - WIFI 优先   * `4g` - 4G 优先   # noqa: E501

        :return: The priority of this RouteStatus.  # noqa: E501
        :rtype: str
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this RouteStatus.

        路由优先级选择:   * `wifi` - WIFI 优先   * `4g` - 4G 优先   # noqa: E501

        :param priority: The priority of this RouteStatus.  # noqa: E501
        :type: str
        """
        allowed_values = ["wifi", "4g"]  # noqa: E501
        if priority not in allowed_values:
            raise ValueError(
                "Invalid value for `priority` ({0}), must be one of {1}"  # noqa: E501
                .format(priority, allowed_values)
            )

        self._priority = priority

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RouteStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RouteStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
