# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SensorMaskCtrlData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'float',
        'is_always': 'bool',
        'is_enabled': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'is_always': 'isAlways',
        'is_enabled': 'isEnabled'
    }

    def __init__(self, id=None, is_always=None, is_enabled=None):  # noqa: E501
        """SensorMaskCtrlData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._is_always = None
        self._is_enabled = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if is_always is not None:
            self.is_always = is_always
        if is_enabled is not None:
            self.is_enabled = is_enabled

    @property
    def id(self):
        """Gets the id of this SensorMaskCtrlData.  # noqa: E501


        :return: The id of this SensorMaskCtrlData.  # noqa: E501
        :rtype: float
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SensorMaskCtrlData.


        :param id: The id of this SensorMaskCtrlData.  # noqa: E501
        :type: float
        """

        self._id = id

    @property
    def is_always(self):
        """Gets the is_always of this SensorMaskCtrlData.  # noqa: E501


        :return: The is_always of this SensorMaskCtrlData.  # noqa: E501
        :rtype: bool
        """
        return self._is_always

    @is_always.setter
    def is_always(self, is_always):
        """Sets the is_always of this SensorMaskCtrlData.


        :param is_always: The is_always of this SensorMaskCtrlData.  # noqa: E501
        :type: bool
        """

        self._is_always = is_always

    @property
    def is_enabled(self):
        """Gets the is_enabled of this SensorMaskCtrlData.  # noqa: E501


        :return: The is_enabled of this SensorMaskCtrlData.  # noqa: E501
        :rtype: bool
        """
        return self._is_enabled

    @is_enabled.setter
    def is_enabled(self, is_enabled):
        """Sets the is_enabled of this SensorMaskCtrlData.


        :param is_enabled: The is_enabled of this SensorMaskCtrlData.  # noqa: E501
        :type: bool
        """

        self._is_enabled = is_enabled

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorMaskCtrlData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorMaskCtrlData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
