# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SensorDisableAreaMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sensor_type': 'str'
    }

    attribute_map = {
        'sensor_type': 'sensor_type'
    }

    def __init__(self, sensor_type=None):  # noqa: E501
        """SensorDisableAreaMetadata - a model defined in Swagger"""  # noqa: E501
        self._sensor_type = None
        self.discriminator = None
        if sensor_type is not None:
            self.sensor_type = sensor_type

    @property
    def sensor_type(self):
        """Gets the sensor_type of this SensorDisableAreaMetadata.  # noqa: E501

        传感器类型，0 碰撞，1 跌落，2 超声，3 深度  # noqa: E501

        :return: The sensor_type of this SensorDisableAreaMetadata.  # noqa: E501
        :rtype: str
        """
        return self._sensor_type

    @sensor_type.setter
    def sensor_type(self, sensor_type):
        """Sets the sensor_type of this SensorDisableAreaMetadata.

        传感器类型，0 碰撞，1 跌落，2 超声，3 深度  # noqa: E501

        :param sensor_type: The sensor_type of this SensorDisableAreaMetadata.  # noqa: E501
        :type: str
        """

        self._sensor_type = sensor_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SensorDisableAreaMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SensorDisableAreaMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
