# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TasksEventsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_id': 'str',
        'status': 'str'
    }

    attribute_map = {
        'task_id': 'task_id',
        'status': 'status'
    }

    def __init__(self, task_id=None, status=None):  # noqa: E501
        """TasksEventsBody - a model defined in Swagger"""  # noqa: E501
        self._task_id = None
        self._status = None
        self.discriminator = None
        if task_id is not None:
            self.task_id = task_id
        if status is not None:
            self.status = status

    @property
    def task_id(self):
        """Gets the task_id of this TasksEventsBody.  # noqa: E501


        :return: The task_id of this TasksEventsBody.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this TasksEventsBody.


        :param task_id: The task_id of this TasksEventsBody.  # noqa: E501
        :type: str
        """

        self._task_id = task_id

    @property
    def status(self):
        """Gets the status of this TasksEventsBody.  # noqa: E501

        任务状态，RUNNING：开始执行任务，FAILED：任务失败，SUCCEEDED：任务成功完成  # noqa: E501

        :return: The status of this TasksEventsBody.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TasksEventsBody.

        任务状态，RUNNING：开始执行任务，FAILED：任务失败，SUCCEEDED：任务成功完成  # noqa: E501

        :param status: The status of this TasksEventsBody.  # noqa: E501
        :type: str
        """
        allowed_values = ["RUNNING", "SUCCEEDED", "FAILED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TasksEventsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TasksEventsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
