# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskTemplateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'name': 'str',
        'action_list': 'list[TaskOperation]'
    }

    attribute_map = {
        'key': 'key',
        'name': 'name',
        'action_list': 'action_list'
    }

    def __init__(self, key=None, name=None, action_list=None):  # noqa: E501
        """TaskTemplateRequest - a model defined in Swagger"""  # noqa: E501
        self._key = None
        self._name = None
        self._action_list = None
        self.discriminator = None
        if key is not None:
            self.key = key
        if name is not None:
            self.name = name
        if action_list is not None:
            self.action_list = action_list

    @property
    def key(self):
        """Gets the key of this TaskTemplateRequest.  # noqa: E501

        任务模板ID  # noqa: E501

        :return: The key of this TaskTemplateRequest.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this TaskTemplateRequest.

        任务模板ID  # noqa: E501

        :param key: The key of this TaskTemplateRequest.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def name(self):
        """Gets the name of this TaskTemplateRequest.  # noqa: E501

        任务模板名称  # noqa: E501

        :return: The name of this TaskTemplateRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TaskTemplateRequest.

        任务模板名称  # noqa: E501

        :param name: The name of this TaskTemplateRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def action_list(self):
        """Gets the action_list of this TaskTemplateRequest.  # noqa: E501

        任务点位列表  # noqa: E501

        :return: The action_list of this TaskTemplateRequest.  # noqa: E501
        :rtype: list[TaskOperation]
        """
        return self._action_list

    @action_list.setter
    def action_list(self, action_list):
        """Sets the action_list of this TaskTemplateRequest.

        任务点位列表  # noqa: E501

        :param action_list: The action_list of this TaskTemplateRequest.  # noqa: E501
        :type: list[TaskOperation]
        """

        self._action_list = action_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskTemplateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskTemplateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
