# coding: utf-8

"""
    Slamware RESTful API

    本文档适用于思岚科技旗下的各类底盘和服务机器人产品.  # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskOperation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'display_name': 'str',
        'action': 'str',
        'wait_time': 'int'
    }

    attribute_map = {
        'display_name': 'display_name',
        'action': 'action',
        'wait_time': 'wait_time'
    }

    def __init__(self, display_name=None, action=None, wait_time=None):  # noqa: E501
        """TaskOperation - a model defined in Swagger"""  # noqa: E501
        self._display_name = None
        self._action = None
        self._wait_time = None
        self.discriminator = None
        if display_name is not None:
            self.display_name = display_name
        if action is not None:
            self.action = action
        if wait_time is not None:
            self.wait_time = wait_time

    @property
    def display_name(self):
        """Gets the display_name of this TaskOperation.  # noqa: E501

        目标点位POI的display_name  # noqa: E501

        :return: The display_name of this TaskOperation.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this TaskOperation.

        目标点位POI的display_name  # noqa: E501

        :param display_name: The display_name of this TaskOperation.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    @property
    def action(self):
        """Gets the action of this TaskOperation.  # noqa: E501

        机器人在目标点位需要执行的操作  # noqa: E501

        :return: The action of this TaskOperation.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this TaskOperation.

        机器人在目标点位需要执行的操作  # noqa: E501

        :param action: The action of this TaskOperation.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def wait_time(self):
        """Gets the wait_time of this TaskOperation.  # noqa: E501

        机器人在目标点位完成操作后的等待时间，单位秒  # noqa: E501

        :return: The wait_time of this TaskOperation.  # noqa: E501
        :rtype: int
        """
        return self._wait_time

    @wait_time.setter
    def wait_time(self, wait_time):
        """Sets the wait_time of this TaskOperation.

        机器人在目标点位完成操作后的等待时间，单位秒  # noqa: E501

        :param wait_time: The wait_time of this TaskOperation.  # noqa: E501
        :type: int
        """

        self._wait_time = wait_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskOperation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskOperation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
